# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'springMagic_jpn.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_SpringMagic_mainWindow(object):
    def setupUi(self, SpringMagic_mainWindow):
        if not SpringMagic_mainWindow.objectName():
            SpringMagic_mainWindow.setObjectName(u"SpringMagic_mainWindow")
        SpringMagic_mainWindow.setWindowModality(Qt.NonModal)
        SpringMagic_mainWindow.setEnabled(True)
        SpringMagic_mainWindow.resize(380, 425)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SpringMagic_mainWindow.sizePolicy().hasHeightForWidth())
        SpringMagic_mainWindow.setSizePolicy(sizePolicy)
        SpringMagic_mainWindow.setMinimumSize(QSize(380, 425))
        SpringMagic_mainWindow.setMaximumSize(QSize(380, 655))
        SpringMagic_mainWindow.setCursor(QCursor(Qt.ArrowCursor))
        SpringMagic_mainWindow.setMouseTracking(False)
        SpringMagic_mainWindow.setFocusPolicy(Qt.NoFocus)
        SpringMagic_mainWindow.setWindowTitle(u"Spring Magic 3.5a        Yanbin Bai")
        icon = QIcon()
        icon.addFile(u"icons/Title.png", QSize(), QIcon.Normal, QIcon.Off)
        SpringMagic_mainWindow.setWindowIcon(icon)
        SpringMagic_mainWindow.setIconSize(QSize(24, 24))
        SpringMagic_mainWindow.setToolButtonStyle(Qt.ToolButtonIconOnly)
        SpringMagic_mainWindow.setAnimated(True)
        SpringMagic_mainWindow.setTabShape(QTabWidget.Rounded)
        SpringMagic_mainWindow.setDockNestingEnabled(False)
        self.main_actionReset = QAction(SpringMagic_mainWindow)
        self.main_actionReset.setObjectName(u"main_actionReset")
        self.main_actionReset.setEnabled(False)
        self.main_actionAbout = QAction(SpringMagic_mainWindow)
        self.main_actionAbout.setObjectName(u"main_actionAbout")
        self.main_actionAbout.setCheckable(False)
        self.main_actionAbout.setChecked(False)
        self.main_actionAbout.setEnabled(False)
        self.main_actionAbout.setMenuRole(QAction.AboutRole)
        self.centralwidget = QWidget(SpringMagic_mainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.main_tab = QTabWidget(self.centralwidget)
        self.main_tab.setObjectName(u"main_tab")
        self.main_tab.setEnabled(True)
        self.main_tab.setGeometry(QRect(0, 0, 381, 341))
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.main_tab.sizePolicy().hasHeightForWidth())
        self.main_tab.setSizePolicy(sizePolicy1)
        font = QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.main_tab.setFont(font)
        self.main_tab.setMouseTracking(False)
        self.main_tab.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.main_tab.setAcceptDrops(True)
        self.main_tab.setAutoFillBackground(False)
        self.main_tab.setTabPosition(QTabWidget.North)
        self.main_tab.setTabShape(QTabWidget.Rounded)
        self.main_tab.setElideMode(Qt.ElideNone)
        self.main_tab.setUsesScrollButtons(True)
        self.main_tab.setDocumentMode(False)
        self.main_tab.setTabsClosable(False)
        self.main_tab.setMovable(False)
        self.main_tab.setProperty("tabBarAutoHide", True)
        self.donate_tab = QWidget()
        self.donate_tab.setObjectName(u"donate_tab")
        self.eng_groupBox = QGroupBox(self.donate_tab)
        self.eng_groupBox.setObjectName(u"eng_groupBox")
        self.eng_groupBox.setGeometry(QRect(10, 10, 351, 291))
        font1 = QFont()
        font1.setBold(True)
        font1.setWeight(75)
        self.eng_groupBox.setFont(font1)
        self.eng_groupBox.setFlat(False)
        self.donatePayPal_button = QPushButton(self.eng_groupBox)
        self.donatePayPal_button.setObjectName(u"donatePayPal_button")
        self.donatePayPal_button.setGeometry(QRect(150, 200, 51, 51))
        self.donatePayPal_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon1 = QIcon()
        icon1.addFile(u"icons/paypal.png", QSize(), QIcon.Normal, QIcon.Off)
        self.donatePayPal_button.setIcon(icon1)
        self.donatePayPal_button.setIconSize(QSize(40, 40))
        self.donatePayPal_button.setFlat(True)
        self.label_3 = QLabel(self.eng_groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 160, 121, 121))
        self.label_3.setPixmap(QPixmap(u"icons/ali_pay.png"))
        self.label_21 = QLabel(self.eng_groupBox)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(220, 160, 121, 121))
        self.label_21.setMouseTracking(True)
        self.label_21.setPixmap(QPixmap(u"icons/wechat_pay.png"))
        self.label_22 = QLabel(self.eng_groupBox)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(4, 20, 351, 81))
        self.label = QLabel(self.eng_groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 110, 331, 31))
        font2 = QFont()
        font2.setFamily(u"Microsoft Sans Serif")
        font2.setPointSize(10)
        font2.setBold(False)
        font2.setWeight(50)
        self.label.setFont(font2)
        icon2 = QIcon()
        icon2.addFile(u"icons/donut.png", QSize(), QIcon.Normal, QIcon.Off)
        self.main_tab.addTab(self.donate_tab, icon2, "")
        self.spring_tab = QWidget()
        self.spring_tab.setObjectName(u"spring_tab")
        self.spring_groupBox = QGroupBox(self.spring_tab)
        self.spring_groupBox.setObjectName(u"spring_groupBox")
        self.spring_groupBox.setEnabled(True)
        self.spring_groupBox.setGeometry(QRect(10, -30, 361, 341))
        self.spring_groupBox.setFlat(True)
        self.springSpring_lineEdit = QLineEdit(self.spring_groupBox)
        self.springSpring_lineEdit.setObjectName(u"springSpring_lineEdit")
        self.springSpring_lineEdit.setGeometry(QRect(30, 56, 31, 20))
        self.springSpring_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_24 = QLabel(self.spring_groupBox)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(20, 40, 71, 16))
        font3 = QFont()
        font3.setPointSize(9)
        self.label_24.setFont(font3)
        self.label_25 = QLabel(self.spring_groupBox)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(160, -68, 31, 16))
        self.springSubs_lineEdit = QLineEdit(self.spring_groupBox)
        self.springSubs_lineEdit.setObjectName(u"springSubs_lineEdit")
        self.springSubs_lineEdit.setGeometry(QRect(190, -70, 31, 20))
        self.label_26 = QLabel(self.spring_groupBox)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(96, 40, 61, 16))
        self.label_26.setFont(font3)
        self.springXspring_lineEdit = QLineEdit(self.spring_groupBox)
        self.springXspring_lineEdit.setObjectName(u"springXspring_lineEdit")
        self.springXspring_lineEdit.setGeometry(QRect(101, 57, 31, 20))
        self.springXspring_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.springBonePose_groupBox = QGroupBox(self.spring_groupBox)
        self.springBonePose_groupBox.setObjectName(u"springBonePose_groupBox")
        self.springBonePose_groupBox.setGeometry(QRect(10, 230, 141, 101))
        self.springBonePose_groupBox.setFont(font3)
        self.springBindPose_button = QPushButton(self.springBonePose_groupBox)
        self.springBindPose_button.setObjectName(u"springBindPose_button")
        self.springBindPose_button.setGeometry(QRect(4, 20, 91, 31))
        self.springBindPose_button.setFont(font3)
        self.springStraight_button = QPushButton(self.springBonePose_groupBox)
        self.springStraight_button.setObjectName(u"springStraight_button")
        self.springStraight_button.setGeometry(QRect(4, 60, 71, 31))
        self.springStraight_button.setFont(font3)
        self.springCopy_button = QPushButton(self.springBonePose_groupBox)
        self.springCopy_button.setObjectName(u"springCopy_button")
        self.springCopy_button.setGeometry(QRect(97, 20, 41, 31))
        self.springCopy_button.setFont(font3)
        self.springPaste_button = QPushButton(self.springBonePose_groupBox)
        self.springPaste_button.setObjectName(u"springPaste_button")
        self.springPaste_button.setGeometry(QRect(87, 60, 51, 31))
        self.springPaste_button.setFont(font3)
        self.springApply_Button = QPushButton(self.spring_groupBox)
        self.springApply_Button.setObjectName(u"springApply_Button")
        self.springApply_Button.setGeometry(QRect(260, 280, 81, 51))
        font4 = QFont()
        font4.setPointSize(12)
        font4.setBold(True)
        font4.setWeight(75)
        self.springApply_Button.setFont(font4)
        self.label_29 = QLabel(self.spring_groupBox)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(420, 40, 41, 16))
        self.collision_groupBox = QGroupBox(self.spring_groupBox)
        self.collision_groupBox.setObjectName(u"collision_groupBox")
        self.collision_groupBox.setGeometry(QRect(10, 160, 331, 61))
        self.collision_groupBox.setFont(font3)
        self.springCapsule_checkBox = QCheckBox(self.collision_groupBox)
        self.springCapsule_checkBox.setObjectName(u"springCapsule_checkBox")
        self.springCapsule_checkBox.setGeometry(QRect(10, 30, 81, 17))
        self.springCapsule_checkBox.setFont(font3)
        self.springAddBody_Button = QPushButton(self.collision_groupBox)
        self.springAddBody_Button.setObjectName(u"springAddBody_Button")
        self.springAddBody_Button.setEnabled(True)
        self.springAddBody_Button.setGeometry(QRect(180, 14, 41, 41))
        icon3 = QIcon()
        icon3.addFile(u"icons/addCapsule.png", QSize(), QIcon.Normal, QIcon.Off)
        self.springAddBody_Button.setIcon(icon3)
        self.springAddBody_Button.setIconSize(QSize(32, 32))
        self.springAddBody_Button.setCheckable(False)
        self.springAddBody_Button.setFlat(False)
        self.springClearBody_Button = QPushButton(self.collision_groupBox)
        self.springClearBody_Button.setObjectName(u"springClearBody_Button")
        self.springClearBody_Button.setEnabled(True)
        self.springClearBody_Button.setGeometry(QRect(280, 14, 41, 41))
        icon4 = QIcon()
        icon4.addFile(u"icons/clearCapsule.png", QSize(), QIcon.Normal, QIcon.Off)
        self.springClearBody_Button.setIcon(icon4)
        self.springClearBody_Button.setIconSize(QSize(32, 32))
        self.springFastMove_checkBox = QCheckBox(self.collision_groupBox)
        self.springFastMove_checkBox.setObjectName(u"springFastMove_checkBox")
        self.springFastMove_checkBox.setEnabled(False)
        self.springFastMove_checkBox.setGeometry(QRect(90, 30, 75, 17))
        self.springFastMove_checkBox.setFont(font3)
        self.springFloor_checkBox = QCheckBox(self.collision_groupBox)
        self.springFloor_checkBox.setObjectName(u"springFloor_checkBox")
        self.springFloor_checkBox.setGeometry(QRect(380, 22, 50, 16))
        self.springFloor_checkBox.setChecked(False)
        self.springFloor_lineEdit = QLineEdit(self.collision_groupBox)
        self.springFloor_lineEdit.setObjectName(u"springFloor_lineEdit")
        self.springFloor_lineEdit.setEnabled(False)
        self.springFloor_lineEdit.setGeometry(QRect(430, 20, 31, 20))
        self.springFloor_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.springAddPlane_Button = QPushButton(self.collision_groupBox)
        self.springAddPlane_Button.setObjectName(u"springAddPlane_Button")
        self.springAddPlane_Button.setEnabled(True)
        self.springAddPlane_Button.setGeometry(QRect(230, 14, 41, 41))
        icon5 = QIcon()
        icon5.addFile(u"icons/addPlane.png", QSize(), QIcon.Normal, QIcon.Off)
        self.springAddPlane_Button.setIcon(icon5)
        self.springAddPlane_Button.setIconSize(QSize(32, 32))
        self.springAddPlane_Button.setCheckable(False)
        self.springAddPlane_Button.setFlat(False)
        self.label_30 = QLabel(self.spring_groupBox)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setEnabled(False)
        self.label_30.setGeometry(QRect(240, -30, 61, 16))
        self.label_30.setFont(font3)
        self.springTension_lineEdit = QLineEdit(self.spring_groupBox)
        self.springTension_lineEdit.setObjectName(u"springTension_lineEdit")
        self.springTension_lineEdit.setEnabled(False)
        self.springTension_lineEdit.setGeometry(QRect(250, -10, 31, 20))
        self.springTension_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.keyRange_groupBox = QGroupBox(self.spring_groupBox)
        self.keyRange_groupBox.setObjectName(u"keyRange_groupBox")
        self.keyRange_groupBox.setGeometry(QRect(10, 80, 331, 71))
        self.keyRange_groupBox.setFont(font3)
        self.springClearSubFrame_checkBox = QCheckBox(self.keyRange_groupBox)
        self.springClearSubFrame_checkBox.setObjectName(u"springClearSubFrame_checkBox")
        self.springClearSubFrame_checkBox.setEnabled(False)
        self.springClearSubFrame_checkBox.setGeometry(QRect(110, 50, 71, 16))
        self.springClearSubFrame_checkBox.setFont(font3)
        self.springClearSubFrame_checkBox.setChecked(True)
        self.label_31 = QLabel(self.keyRange_groupBox)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setEnabled(False)
        self.label_31.setGeometry(QRect(10, 50, 61, 16))
        self.label_31.setFont(font3)
        self.springSubDiv_lineEdit = QLineEdit(self.keyRange_groupBox)
        self.springSubDiv_lineEdit.setObjectName(u"springSubDiv_lineEdit")
        self.springSubDiv_lineEdit.setEnabled(False)
        self.springSubDiv_lineEdit.setGeometry(QRect(70, 48, 31, 20))
        self.springSubDiv_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.springActive_radioButton = QRadioButton(self.keyRange_groupBox)
        self.springActive_radioButton.setObjectName(u"springActive_radioButton")
        self.springActive_radioButton.setGeometry(QRect(30, 20, 91, 17))
        self.springActive_radioButton.setChecked(True)
        self.springFrom_radioButton = QRadioButton(self.keyRange_groupBox)
        self.springFrom_radioButton.setObjectName(u"springFrom_radioButton")
        self.springFrom_radioButton.setGeometry(QRect(140, 20, 51, 17))
        self.springFrom_radioButton.setFont(font3)
        self.springFrom_lineEdit = QLineEdit(self.keyRange_groupBox)
        self.springFrom_lineEdit.setObjectName(u"springFrom_lineEdit")
        self.springFrom_lineEdit.setEnabled(False)
        self.springFrom_lineEdit.setGeometry(QRect(190, 20, 31, 20))
        self.springFrom_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_28 = QLabel(self.keyRange_groupBox)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(240, 20, 31, 16))
        self.label_28.setFont(font3)
        self.springEnd_lineEdit = QLineEdit(self.keyRange_groupBox)
        self.springEnd_lineEdit.setObjectName(u"springEnd_lineEdit")
        self.springEnd_lineEdit.setEnabled(False)
        self.springEnd_lineEdit.setGeometry(QRect(280, 20, 31, 20))
        self.springEnd_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.springLoop_checkBox = QCheckBox(self.keyRange_groupBox)
        self.springLoop_checkBox.setObjectName(u"springLoop_checkBox")
        self.springLoop_checkBox.setGeometry(QRect(274, 50, 51, 16))
        self.springLoop_checkBox.setFont(font3)
        self.springLoop_checkBox.setChecked(False)
        self.springPoseMatch_checkBox = QCheckBox(self.keyRange_groupBox)
        self.springPoseMatch_checkBox.setObjectName(u"springPoseMatch_checkBox")
        self.springPoseMatch_checkBox.setEnabled(True)
        self.springPoseMatch_checkBox.setGeometry(QRect(190, 50, 81, 16))
        font5 = QFont()
        font5.setPointSize(8)
        self.springPoseMatch_checkBox.setFont(font5)
        self.springPoseMatch_checkBox.setCheckable(True)
        self.springPoseMatch_checkBox.setChecked(False)
        self.springWind_Button = QPushButton(self.spring_groupBox)
        self.springWind_Button.setObjectName(u"springWind_Button")
        self.springWind_Button.setGeometry(QRect(260, 240, 81, 31))
        self.springWind_Button.setFont(font)
        icon6 = QIcon()
        icon6.addFile(u"icons/wind.png", QSize(), QIcon.Normal, QIcon.Off)
        self.springWind_Button.setIcon(icon6)
        self.springWind_Button.setIconSize(QSize(24, 24))
        self.ctrl_groupBox = QGroupBox(self.spring_groupBox)
        self.ctrl_groupBox.setObjectName(u"ctrl_groupBox")
        self.ctrl_groupBox.setGeometry(QRect(160, 230, 91, 101))
        self.ctrl_groupBox.setFont(font3)
        self.springBind_Button = QPushButton(self.ctrl_groupBox)
        self.springBind_Button.setObjectName(u"springBind_Button")
        self.springBind_Button.setGeometry(QRect(5, 20, 81, 31))
        self.springBind_Button.setFont(font)
        icon7 = QIcon()
        icon7.addFile(u"icons/ctrl_bind.png", QSize(), QIcon.Normal, QIcon.Off)
        self.springBind_Button.setIcon(icon7)
        self.springBind_Button.setIconSize(QSize(24, 24))
        self.springBake_Button = QPushButton(self.ctrl_groupBox)
        self.springBake_Button.setObjectName(u"springBake_Button")
        self.springBake_Button.setEnabled(True)
        self.springBake_Button.setGeometry(QRect(10, 60, 71, 31))
        self.springBake_Button.setFont(font3)
        icon8 = QIcon()
        icon8.addFile(u"icons/ctrl_bake.png", QSize(), QIcon.Normal, QIcon.Off)
        self.springBake_Button.setIcon(icon8)
        self.springBake_Button.setIconSize(QSize(24, 24))
        self.label_27 = QLabel(self.spring_groupBox)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(170, 40, 61, 16))
        self.label_27.setFont(font3)
        self.springExtend_lineEdit = QLineEdit(self.spring_groupBox)
        self.springExtend_lineEdit.setObjectName(u"springExtend_lineEdit")
        self.springExtend_lineEdit.setGeometry(QRect(180, 57, 31, 20))
        self.springExtend_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_32 = QLabel(self.spring_groupBox)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(270, 40, 41, 16))
        self.label_32.setFont(font5)
        self.springInertia_lineEdit = QLineEdit(self.spring_groupBox)
        self.springInertia_lineEdit.setObjectName(u"springInertia_lineEdit")
        self.springInertia_lineEdit.setGeometry(QRect(266, 56, 31, 20))
        self.springInertia_lineEdit.setFont(font5)
        self.springInertia_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.shelf_button = QPushButton(self.spring_groupBox)
        self.shelf_button.setObjectName(u"shelf_button")
        self.shelf_button.setGeometry(QRect(310, 40, 30, 30))
        sizePolicy2 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.shelf_button.sizePolicy().hasHeightForWidth())
        self.shelf_button.setSizePolicy(sizePolicy2)
        self.shelf_button.setLayoutDirection(Qt.LeftToRight)
        self.shelf_button.setAutoFillBackground(False)
        icon9 = QIcon()
        icon9.addFile(u"icons/Shelf.png", QSize(), QIcon.Normal, QIcon.Off)
        self.shelf_button.setIcon(icon9)
        self.shelf_button.setIconSize(QSize(30, 30))
        self.shelf_button.setCheckable(False)
        self.shelf_button.setAutoRepeat(False)
        self.shelf_button.setAutoExclusive(False)
        self.shelf_button.setFlat(True)
        self.label_24.raise_()
        self.keyRange_groupBox.raise_()
        self.springSpring_lineEdit.raise_()
        self.label_25.raise_()
        self.springSubs_lineEdit.raise_()
        self.label_26.raise_()
        self.springXspring_lineEdit.raise_()
        self.springBonePose_groupBox.raise_()
        self.springApply_Button.raise_()
        self.label_29.raise_()
        self.collision_groupBox.raise_()
        self.label_30.raise_()
        self.springTension_lineEdit.raise_()
        self.springWind_Button.raise_()
        self.ctrl_groupBox.raise_()
        self.label_27.raise_()
        self.springExtend_lineEdit.raise_()
        self.label_32.raise_()
        self.springInertia_lineEdit.raise_()
        self.shelf_button.raise_()
        icon10 = QIcon()
        icon10.addFile(u"icons/spring.png", QSize(), QIcon.Normal, QIcon.Off)
        self.main_tab.addTab(self.spring_tab, icon10, "")
        self.main_textEdit = QTextEdit(self.centralwidget)
        self.main_textEdit.setObjectName(u"main_textEdit")
        self.main_textEdit.setGeometry(QRect(10, 410, 345, 200))
        sizePolicy3 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy3.setHorizontalStretch(200)
        sizePolicy3.setVerticalStretch(200)
        sizePolicy3.setHeightForWidth(self.main_textEdit.sizePolicy().hasHeightForWidth())
        self.main_textEdit.setSizePolicy(sizePolicy3)
        self.main_textEdit.setMinimumSize(QSize(345, 40))
        self.main_textEdit.setMaximumSize(QSize(345, 200))
        self.main_textEdit.setFont(font5)
        self.main_textEdit.setReadOnly(True)
        self.main_progressBar = QProgressBar(self.centralwidget)
        self.main_progressBar.setObjectName(u"main_progressBar")
        self.main_progressBar.setGeometry(QRect(10, 375, 361, 27))
        font6 = QFont()
        font6.setFamily(u"Consolas")
        font6.setPointSize(12)
        self.main_progressBar.setFont(font6)
        self.main_progressBar.setAcceptDrops(False)
        self.main_progressBar.setValue(0)
        self.main_progressBar.setAlignment(Qt.AlignCenter)
        self.main_progressBar.setTextVisible(True)
        self.main_progressBar.setOrientation(Qt.Horizontal)
        self.main_progressBar.setInvertedAppearance(False)
        self.main_progressBar.setTextDirection(QProgressBar.TopToBottom)
        self.main_processLabel = QLabel(self.centralwidget)
        self.main_processLabel.setObjectName(u"main_processLabel")
        self.main_processLabel.setGeometry(QRect(13, 353, 231, 16))
        self.main_processLabel.setFont(font5)
        self.main_processLabel.setText(u"")
        self.main_processLabel.setTextFormat(Qt.PlainText)
        self.main_processLabel.setTextInteractionFlags(Qt.LinksAccessibleByMouse|Qt.TextSelectableByMouse)
        self.link_pushButton = QPushButton(self.centralwidget)
        self.link_pushButton.setObjectName(u"link_pushButton")
        self.link_pushButton.setEnabled(True)
        self.link_pushButton.setGeometry(QRect(340, 342, 31, 31))
        font7 = QFont()
        font7.setUnderline(False)
        self.link_pushButton.setFont(font7)
        self.link_pushButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.link_pushButton.setMouseTracking(False)
        self.link_pushButton.setFocusPolicy(Qt.NoFocus)
        self.link_pushButton.setAutoFillBackground(False)
        icon11 = QIcon()
        icon11.addFile(u"icons/linkedin.png", QSize(), QIcon.Normal, QIcon.Off)
        self.link_pushButton.setIcon(icon11)
        self.link_pushButton.setIconSize(QSize(25, 25))
        self.link_pushButton.setCheckable(False)
        self.link_pushButton.setChecked(False)
        self.link_pushButton.setAutoDefault(False)
        self.link_pushButton.setFlat(True)
        self.miscUpdate_pushButton = QPushButton(self.centralwidget)
        self.miscUpdate_pushButton.setObjectName(u"miscUpdate_pushButton")
        self.miscUpdate_pushButton.setGeometry(QRect(220, 342, 31, 30))
        sizePolicy2.setHeightForWidth(self.miscUpdate_pushButton.sizePolicy().hasHeightForWidth())
        self.miscUpdate_pushButton.setSizePolicy(sizePolicy2)
        self.miscUpdate_pushButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.miscUpdate_pushButton.setLayoutDirection(Qt.LeftToRight)
        self.miscUpdate_pushButton.setAutoFillBackground(False)
        icon12 = QIcon()
        icon12.addFile(u"icons/update.png", QSize(), QIcon.Normal, QIcon.Off)
        self.miscUpdate_pushButton.setIcon(icon12)
        self.miscUpdate_pushButton.setIconSize(QSize(25, 25))
        self.miscUpdate_pushButton.setCheckable(False)
        self.miscUpdate_pushButton.setAutoRepeat(False)
        self.miscUpdate_pushButton.setAutoExclusive(False)
        self.miscUpdate_pushButton.setFlat(True)
        self.vimeo_pushButton = QPushButton(self.centralwidget)
        self.vimeo_pushButton.setObjectName(u"vimeo_pushButton")
        self.vimeo_pushButton.setEnabled(True)
        self.vimeo_pushButton.setGeometry(QRect(280, 342, 31, 31))
        self.vimeo_pushButton.setFont(font7)
        self.vimeo_pushButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.vimeo_pushButton.setMouseTracking(False)
        self.vimeo_pushButton.setFocusPolicy(Qt.NoFocus)
        self.vimeo_pushButton.setAutoFillBackground(False)
        icon13 = QIcon()
        icon13.addFile(u"icons/youtube.png", QSize(), QIcon.Normal, QIcon.Off)
        self.vimeo_pushButton.setIcon(icon13)
        self.vimeo_pushButton.setIconSize(QSize(25, 25))
        self.vimeo_pushButton.setCheckable(False)
        self.vimeo_pushButton.setChecked(False)
        self.vimeo_pushButton.setAutoDefault(False)
        self.vimeo_pushButton.setFlat(True)
        self.bilibili_pushButton = QPushButton(self.centralwidget)
        self.bilibili_pushButton.setObjectName(u"bilibili_pushButton")
        self.bilibili_pushButton.setEnabled(True)
        self.bilibili_pushButton.setGeometry(QRect(250, 342, 31, 31))
        self.bilibili_pushButton.setFont(font7)
        self.bilibili_pushButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.bilibili_pushButton.setMouseTracking(False)
        self.bilibili_pushButton.setFocusPolicy(Qt.NoFocus)
        self.bilibili_pushButton.setAutoFillBackground(False)
        icon14 = QIcon()
        icon14.addFile(u"icons/bilibili.png", QSize(), QIcon.Normal, QIcon.Off)
        self.bilibili_pushButton.setIcon(icon14)
        self.bilibili_pushButton.setIconSize(QSize(25, 25))
        self.bilibili_pushButton.setCheckable(False)
        self.bilibili_pushButton.setChecked(False)
        self.bilibili_pushButton.setAutoDefault(False)
        self.bilibili_pushButton.setFlat(True)
        self.spring_language_list = QListWidget(self.centralwidget)
        icon15 = QIcon()
        icon15.addFile(u"icons/China Flag.png", QSize(), QIcon.Normal, QIcon.Off)
        __qlistwidgetitem = QListWidgetItem(self.spring_language_list)
        __qlistwidgetitem.setTextAlignment(Qt.AlignHCenter|Qt.AlignVCenter|Qt.AlignCenter);
        __qlistwidgetitem.setIcon(icon15);
        __qlistwidgetitem.setFlags(Qt.ItemIsSelectable|Qt.ItemIsEnabled);
        icon16 = QIcon()
        icon16.addFile(u"icons/english.png", QSize(), QIcon.Normal, QIcon.Off)
        __qlistwidgetitem1 = QListWidgetItem(self.spring_language_list)
        __qlistwidgetitem1.setTextAlignment(Qt.AlignHCenter|Qt.AlignVCenter|Qt.AlignCenter);
        __qlistwidgetitem1.setIcon(icon16);
        __qlistwidgetitem1.setFlags(Qt.ItemIsSelectable|Qt.ItemIsEnabled);
        icon17 = QIcon()
        icon17.addFile(u"icons/japanese.png", QSize(), QIcon.Normal, QIcon.Off)
        __qlistwidgetitem2 = QListWidgetItem(self.spring_language_list)
        __qlistwidgetitem2.setTextAlignment(Qt.AlignHCenter|Qt.AlignVCenter|Qt.AlignCenter);
        __qlistwidgetitem2.setIcon(icon17);
        __qlistwidgetitem2.setFlags(Qt.ItemIsSelectable|Qt.ItemIsEnabled);
        self.spring_language_list.setObjectName(u"spring_language_list")
        self.spring_language_list.setGeometry(QRect(307, 235, 36, 111))
        font8 = QFont()
        font8.setKerning(False)
        self.spring_language_list.setFont(font8)
        self.spring_language_list.setAutoFillBackground(False)
        self.spring_language_list.setFrameShape(QFrame.NoFrame)
        self.spring_language_list.setFrameShadow(QFrame.Raised)
        self.spring_language_list.setLineWidth(0)
        self.spring_language_list.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.spring_language_list.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.spring_language_list.setFlow(QListView.LeftToRight)
        self.spring_language_list.setGridSize(QSize(36, 36))
        self.spring_language_list.setViewMode(QListView.IconMode)
        self.language_button = QPushButton(self.centralwidget)
        self.language_button.setObjectName(u"language_button")
        self.language_button.setEnabled(True)
        self.language_button.setGeometry(QRect(310, 342, 31, 31))
        self.language_button.setFont(font7)
        self.language_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.language_button.setMouseTracking(False)
        self.language_button.setFocusPolicy(Qt.NoFocus)
        self.language_button.setAutoFillBackground(False)
        icon18 = QIcon()
        icon18.addFile(u"icons/language.png", QSize(), QIcon.Normal, QIcon.Off)
        self.language_button.setIcon(icon18)
        self.language_button.setIconSize(QSize(25, 25))
        self.language_button.setCheckable(False)
        self.language_button.setChecked(False)
        self.language_button.setAutoDefault(False)
        self.language_button.setFlat(True)
        self.main_lang_id = QLabel(self.centralwidget)
        self.main_lang_id.setObjectName(u"main_lang_id")
        self.main_lang_id.setGeometry(QRect(-50, 360, 21, 16))
        self.main_lang_id.setFont(font5)
        self.main_lang_id.setText(u"eng")
        SpringMagic_mainWindow.setCentralWidget(self.centralwidget)
        self.main_processLabel.raise_()
        self.link_pushButton.raise_()
        self.main_tab.raise_()
        self.main_textEdit.raise_()
        self.main_progressBar.raise_()
        self.miscUpdate_pushButton.raise_()
        self.vimeo_pushButton.raise_()
        self.bilibili_pushButton.raise_()
        self.spring_language_list.raise_()
        self.language_button.raise_()
        self.main_lang_id.raise_()
        self.statusbar = QStatusBar(SpringMagic_mainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setEnabled(True)
        SpringMagic_mainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.main_tab, self.main_textEdit)

        self.retranslateUi(SpringMagic_mainWindow)
        self.springCapsule_checkBox.clicked.connect(self.springFastMove_checkBox.setEnabled)
        self.springCapsule_checkBox.clicked.connect(self.label_31.setEnabled)
        self.springCapsule_checkBox.clicked.connect(self.springSubDiv_lineEdit.setEnabled)
        self.springCapsule_checkBox.clicked.connect(self.label_30.setEnabled)
        self.springCapsule_checkBox.clicked.connect(self.springTension_lineEdit.setEnabled)
        self.springFrom_radioButton.toggled.connect(self.springFrom_lineEdit.setEnabled)
        self.springFrom_radioButton.toggled.connect(self.springEnd_lineEdit.setEnabled)
        self.springCapsule_checkBox.clicked.connect(self.springClearSubFrame_checkBox.setEnabled)

        self.main_tab.setCurrentIndex(1)
        self.link_pushButton.setDefault(False)
        self.vimeo_pushButton.setDefault(False)
        self.bilibili_pushButton.setDefault(False)
        self.language_button.setDefault(False)


        QMetaObject.connectSlotsByName(SpringMagic_mainWindow)
    # setupUi

    def retranslateUi(self, SpringMagic_mainWindow):
        self.main_actionReset.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Reset", None))
        self.main_actionAbout.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"About...", None))
#if QT_CONFIG(tooltip)
        self.main_tab.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.main_tab.setStatusTip("")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.main_tab.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.main_tab.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.main_tab.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.eng_groupBox.setTitle(QCoreApplication.translate("SpringMagic_mainWindow", u"\u30b5\u30dd\u30fc\u30c8\u3092\u3088\u308d\u3057\u304f\u304a\u9858\u3044\u3057\u307e\u3059\uff01", None))
#if QT_CONFIG(tooltip)
        self.donatePayPal_button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>PayPal Link</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.donatePayPal_button.setText("")
#if QT_CONFIG(tooltip)
        self.label_3.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>AliPay QR Code</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_3.setText("")
#if QT_CONFIG(tooltip)
        self.label_21.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>WeChat Pay QR Code</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_21.setText("")
        self.label_22.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:8pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-weight:400;\">Spring Magic \u306f\u30d5\u30ea\u30fc\u3067\u63d0\u4f9b\u3057\u3066\u307e\u3059\u306e\u3067\u3001</span><span style=\" font-family:'MS Shell Dlg 2';\">\u3059\u3079\u3066\u306e\u6a5f\u80fd</span><span style=\" font-family:'MS Shell Dlg 2'; font-weight:400;\">\u3092\u7121\u6599\u3067\u4f7f</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-weight:400;\">\u3048\u307e\u3059"
                        "\uff01\u3082\u3057\u3053\u306e\u30b9\u30af\u30ea\u30d7\u30c8\u3092\u4f7f\u3046\u3053\u3068\u3067\u3001\u3042\u306a\u305f\u306e\u4f5c\u696d\u74b0\u5883\u304c\u6539\u5584</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-weight:400;\">\u3059\u308b\u3088\u3046\u3067\u3057\u305f\u3089\u2026</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-size:10pt;\">\u79c1\u306b\u30b3\u30fc\u30d2\u30fc\u4e00\u676f\u3054\u3061\u305d\u3046\u3057\u3066\u3044\u305f\u3060\u3051\u307e\u3059\u304b\uff1f</span></p></body></html>", None))
        self.label.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p><span style=\" font-size:8pt;\">Special Thanks\uff1a</span><span style=\" font-size:8pt; font-weight:600;\">Benoit Degand</span><span style=\" font-size:8pt;\"> help improve performance</span></p></body></html>", None))
        self.main_tab.setTabText(self.main_tab.indexOf(self.donate_tab), QCoreApplication.translate("SpringMagic_mainWindow", u"\u5bc4\u4ed8", None))
        self.spring_groupBox.setTitle(QCoreApplication.translate("SpringMagic_mainWindow", u" Spring Magic ", None))
        self.springSpring_lineEdit.setInputMask("")
        self.springSpring_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"0.7", None))
#if QT_CONFIG(tooltip)
        self.label_24.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>0\u304b\u30891\u307e\u3067\u306e\u5024\u3092\u30bb\u30c3\u30c8\u3057\u307e\u3059\u3002</p><p>\u30b9\u30d7\u30ea\u30f3\u30b0\u306e\u67d4\u3089\u304b\u3055\u3092\u5b9a\u7fa9\u3057\u307e\u3059\u3002\u5927\u304d\u3044\u5024\u307b\u3069\u67d4\u3089\u304b\u3044\u7d50\u679c\u3068\u306a\u308a\u307e\u3059\u3002</p><p>\u91cd\u8981\uff1a\u30b8\u30e7\u30a4\u30f3\u30c8\u30c1\u30a7\u30fc\u30f3\u306f&quot;\u5b50\u306b\u5411\u304b\u3063\u3066X\u8ef8\u65b9\u5411&quot;\u306b\u306e\u307f\u6a5f\u80fd\u3057\u307e\u3059\u3002</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_24.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u30b9\u30d7\u30ea\u30f3\u30b0", None))
        self.label_25.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Subs", None))
        self.springSubs_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"0", None))
#if QT_CONFIG(tooltip)
        self.label_26.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>0\u304b\u30891\u307e\u3067\u306e\u5024\u3092\u30bb\u30c3\u30c8\u3057\u307e\u3059\u3002</p><p>\uff08X\u8ef8\u306b\u5bfe\u3057\uff09\u30c4\u30a4\u30b9\u30c8\u306e\u67d4\u3089\u304b\u3055\u3092\u5b9a\u7fa9\u3057\u307e\u3059\u3002</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_26.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u30c4\u30a4\u30b9\u30c8", None))
        self.springXspring_lineEdit.setInputMask("")
        self.springXspring_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"0.7", None))
        self.springBonePose_groupBox.setTitle(QCoreApplication.translate("SpringMagic_mainWindow", u"\u30dc\u30fc\u30f3\u30dd\u30fc\u30ba", None))
#if QT_CONFIG(tooltip)
        self.springBindPose_button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"\u30d0\u30a4\u30f3\u30c9\u30dd\u30fc\u30ba\u306b\u3057\u307e\u3059\u3002", None))
#endif // QT_CONFIG(tooltip)
        self.springBindPose_button.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u30d0\u30a4\u30f3\u30c9\u30dd\u30fc\u30ba", None))
#if QT_CONFIG(tooltip)
        self.springStraight_button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"\u30b8\u30e7\u30a4\u30f3\u30c8\u30c1\u30a7\u30fc\u30f3\u3092\u307e\u3063\u3059\u3050\u306b\u3057\u307e\u3059\u3002", None))
#endif // QT_CONFIG(tooltip)
        self.springStraight_button.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u30b9\u30c8\u30ec\u30fc\u30c8", None))
#if QT_CONFIG(tooltip)
        self.springCopy_button.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.springCopy_button.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u30b3\u30d4\u30fc", None))
#if QT_CONFIG(tooltip)
        self.springPaste_button.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.springPaste_button.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u30da\u30fc\u30b9\u30c8", None))
#if QT_CONFIG(tooltip)
        self.springApply_Button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u9078\u629e\u3057\u305f\u30aa\u30d6\u30b8\u30a7\u30af\u30c8\u306b\u306e\u307f\u5f71\u97ff\u3057\u307e\u3059\u3002</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springApply_Button.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u9069\u7528", None))
        self.label_29.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"UpAxis", None))
        self.collision_groupBox.setTitle(QCoreApplication.translate("SpringMagic_mainWindow", u" \u885d\u7a81\u5224\u5b9a", None))
#if QT_CONFIG(tooltip)
        self.springCapsule_checkBox.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u30b7\u30fc\u30f3\u5185\u306e\u30ab\u30d7\u30bb\u30eb\u30dc\u30c7\u30a3\u306b\u5bfe\u3059\u308b\u885d\u7a81\u8a08\u7b97\u3092\u30a2\u30af\u30c6\u30a3\u30d6\u306b\u3059\u308b\u3002</p><p>\u8a08\u7b97\u304c\u30b9\u30ed\u30fc\u30c0\u30a6\u30f3\u3059\u308b\u53ef\u80fd\u6027\u304c\u3042\u308a\u307e\u3059\u3002</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springCapsule_checkBox.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u30a2\u30af\u30c6\u30a3\u30d6", None))
#if QT_CONFIG(tooltip)
        self.springAddBody_Button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u9078\u629e\u7269\u306e\u5143\u306e\u4f4d\u7f6e\u306b\u30ab\u30d7\u30bb\u30eb\u3092\u8ffd\u52a0\u3059\u308b\u3001\u3082\u3057\u304f\u306f\u9078\u629e\u3057\u305f\u30dc\u30fc\u30f3\u306b\u3075\u3055\u308f\u3057\u3044\u4f4d\u7f6e\u306b\u30ab\u30d7\u30bb\u30eb\u3092\u8ffd\u52a0\u3057\u307e\u3059\u3002</p><p>\u6ce8\u610f\uff1a\u4e2d\u592e\u306e\u30b7\u30ea\u30f3\u30c0\u30fc\u90e8\u3092\u52d5\u304b\u3057\u305f\u308a\u30b9\u30b1\u30fc\u30eb\u3059\u308b\u3053\u3068\u3067\u3001\u30ab\u30d7\u30bb\u30eb\u3092\u8abf\u6574\u3059\u308b\u3053\u3068\u304c\u3067\u304d\u307e\u3059\u3002\u7570\u306a\u3063\u305f\u30aa\u30d6\u30b8\u30a7\u30af\u30c8\u306b\u30ab\u30d7\u30bb\u30eb\u3092\u30da\u30a2\u30ec\u30f3\u30c8\u3059\u308b\u3068\u3001\u305d\u308c\u3092\u30d5\u30a9\u30ed\u30fc\u3057\u3066\u79fb\u52d5\u3057\u307e\u3059\u3002</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springAddBody_Button.setText("")
#if QT_CONFIG(tooltip)
        self.springClearBody_Button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u30b7\u30fc\u30f3\u4e2d\u306e\u3059\u3079\u3066\u306e\u30ab\u30d7\u30bb\u30eb\u3092\u6d88\u53bb\u3057\u307e\u3059\u3002</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springClearBody_Button.setText("")
#if QT_CONFIG(tooltip)
        self.springFastMove_checkBox.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u30af\u30ea\u30c3\u30af\u3067\u6709\u52b9\u306b\u3059\u308b\u3053\u3068\u3067\u3001\u5168\u901f\u529b\u3067\u52d5\u304f\u8db3\u306e\u3088\u3046\u306a\u9ad8\u901f\u3067\u52d5\u304f\u30dc\u30fc\u30f3\u306b\u30ab\u30d7\u30bb\u30eb\u3092\u30a2\u30bf\u30c3\u30c1\u3057\u305f\u5834\u5408\u3001\u3059\u308a\u629c\u3051\u3092\u6e1b\u5c11\u3059\u308b\u3053\u3068\u304c\u3067\u304d\u307e\u3059\u3002</p><p>\u6ce8\u610f\uff1a\u30ab\u30d7\u30bb\u30eb\u304c\u3086\u3063\u304f\u308a\u3068\u52d5\u304f\u5834\u5408\u306b\u306f\u3001\u30dd\u30c3\u30d4\u30f3\u30b0\u306e\u539f\u56e0\u306b\u306a\u308b\u3053\u3068\u304c\u3042\u308a\u307e\u3059\u3002</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springFastMove_checkBox.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u9ad8\u901f\u79fb\u52d5", None))
#if QT_CONFIG(tooltip)
        self.springFloor_checkBox.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>Add a floor collition for joint chain</p><p>Script will trying to keep all the joints above the hight during caculation</p><p>\u542f\u7528\u5730\u9762\u78b0\u649e\uff0c\u8ba1\u7b97\u65f6\u4f1a\u5c3d\u91cf\u5c06\u9aa8\u9abc\u4fdd\u6301\u5728\u8bbe\u5b9a\u9ad8\u5ea6\u4e4b\u4e0a</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springFloor_checkBox.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Floor", None))
#if QT_CONFIG(tooltip)
        self.springFloor_lineEdit.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>Floor height</p><p>\u5730\u9762\u9ad8\u5ea6</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springFloor_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"0.0", None))
#if QT_CONFIG(tooltip)
        self.springAddPlane_Button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>Create a collision plane</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springAddPlane_Button.setText("")
#if QT_CONFIG(tooltip)
        self.label_30.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u30c1\u30a7\u30fc\u30f3\u306e\u30c6\u30f3\u30b7\u30e7\u30f3\u3001\u3064\u307e\u308a\u30c1\u30a7\u30fc\u30f3\u5168\u4f53\u306b\u3069\u306e\u7a0b\u5ea6\u66f2\u304c\u308b\u529b\u304c\u9069\u7528\u3055\u308c\u308b\u304b\u306e\u5ea6\u5408\u3044\u306f\u3001\u885d\u7a81\u767a\u751f\u6642\u306b\u306e\u307f\u5f71\u97ff\u3057\u307e\u3059\u3002\u885d\u7a81\u306e\u7d50\u679c\u3068\u3057\u3066\u3001\u30dd\u30c3\u30d4\u30f3\u30b0\u3057\u305f\u308a\u30af\u30ea\u30c3\u30d7\u3057\u305f\u308a\u3059\u308b\u306e\u3092\u7de9\u548c\u3067\u304d\u307e\u3059\u3002</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_30.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u30c6\u30f3\u30b7\u30e7\u30f3", None))
        self.springTension_lineEdit.setInputMask("")
        self.springTension_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"0.5", None))
        self.keyRange_groupBox.setTitle(QCoreApplication.translate("SpringMagic_mainWindow", u"\u30ad\u30fc\u7bc4\u56f2", None))
#if QT_CONFIG(tooltip)
        self.springClearSubFrame_checkBox.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u8a08\u7b97\u5f8c\u306e\u30b5\u30d6\u30d5\u30ec\u30fc\u30e0\u4e0a\u306e\u7cbe\u5ea6\u30ad\u30fc\u3092\u53d6\u308a\u9664\u304d\u307e\u3059\u3002</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springClearSubFrame_checkBox.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Wipe Sub", None))
#if QT_CONFIG(tooltip)
        self.label_31.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>1\u30d5\u30ec\u30fc\u30e0\u7d4c\u904e\u3059\u308b\u969b\u306b\u8a55\u4fa1\u3055\u308c\u308b\u30b5\u30d6\u30d5\u30ec\u30fc\u30e0\u6570\u3092\u8a2d\u5b9a\u3059\u308b\u3053\u3068\u3067\u3001\u885d\u7a81\u7269\u306e\u975e\u5e38\u306b\u7d20\u65e9\u3044\u52d5\u304d\u3092\u30ad\u30e3\u30d7\u30c1\u30e3\u3059\u308b\u3053\u3068\u304c\u3067\u304d\u307e\u3059\u3002</p><p>\u30c7\u30d5\u30a9\u30eb\u30c8\u5024\u306f1\u3067\u30015\u3092\u30bb\u30c3\u30c8\u3059\u308c\u30701/5\u30d5\u30ec\u30fc\u30e0\u3054\u3068\u306b\u8a55\u4fa1\u3055\u308c\u307e\u3059\u3002</p><p>\u5024\u3092\u5897\u3084\u3059\u3068\u8a08\u7b97\u6642\u9593\u304c\u5897\u3048\u307e\u3059\u3002</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_31.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Sub-Frame", None))
        self.springSubDiv_lineEdit.setInputMask("")
        self.springSubDiv_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"1", None))
#if QT_CONFIG(tooltip)
        self.springActive_radioButton.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"\u73fe\u5728\u306e\u30bf\u30a4\u30e0\u30e9\u30a4\u30f3\u306e\u7bc4\u56f2", None))
#endif // QT_CONFIG(tooltip)
        self.springActive_radioButton.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u30a2\u30af\u30c6\u30a3\u30d6", None))
        self.springFrom_radioButton.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u59cb\u70b9", None))
        self.springFrom_lineEdit.setInputMask("")
        self.springFrom_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"0", None))
        self.label_28.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u7d42\u70b9", None))
        self.springEnd_lineEdit.setInputMask("")
        self.springEnd_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"200", None))
#if QT_CONFIG(tooltip)
        self.springLoop_checkBox.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u7d50\u679c\u304c\u30eb\u30fc\u30d7\u3059\u308b\u3088\u3046\u306b\u3001\uff12\u56de\u8a08\u7b97\u3057\u307e\u3059\u3002</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springLoop_checkBox.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u30eb\u30fc\u30d7", None))
#if QT_CONFIG(tooltip)
        self.springPoseMatch_checkBox.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>make result close to exists keyframe pose</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springPoseMatch_checkBox.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Pose Match", None))
#if QT_CONFIG(tooltip)
        self.springWind_Button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u30a6\u30a3\u30f3\u30c9\u30b3\u30f3\u30c8\u30ed\u30fc\u30e9\u3092\u8ffd\u52a0\u3057\u307e\u3059\u3002</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springWind_Button.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u30a6\u30a3\u30f3\u30c9", None))
        self.ctrl_groupBox.setTitle(QCoreApplication.translate("SpringMagic_mainWindow", u"\u30b3\u30f3\u30c8\u30ed\u30fc\u30e9\u30fc", None))
#if QT_CONFIG(tooltip)
        self.springBind_Button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u9078\u629e\u3055\u308c\u305f\u30ea\u30b0\u30b3\u30f3\u30c8\u30ed\u30fc\u30e9\u306b\u30dc\u30fc\u30f3\u30c1\u30a7\u30a4\u30f3\u3092\u30d0\u30a4\u30f3\u30c9\u3057\u307e\u3059\u3002</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springBind_Button.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u30d0\u30a4\u30f3\u30c9", None))
#if QT_CONFIG(tooltip)
        self.springBake_Button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u30dc\u30fc\u30f3\u30c1\u30a7\u30a4\u30f3\u306e\u30a2\u30cb\u30e1\u30fc\u30b7\u30e7\u30f3\u3092\u30b3\u30f3\u30c8\u30ed\u30fc\u30e9\u306b\u30d9\u30a4\u30af\u3057\u623b\u3057\u307e\u3059\u3002</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springBake_Button.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u30d9\u30a4\u30af", None))
#if QT_CONFIG(tooltip)
        self.label_27.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"0\u301c1\u306e\u9593\u306b\u8a2d\u5b9a\u3059\u308b\n"
"\u30b9\u30c8\u30e9\u30c3\u30c1\u3068\u30b9\u30ab\u30c3\u30b7\u30e5\u30a2\u30cb\u30e1\u30fc\u30b7\u30e7\u30f3\u3092\u751f\u6210\u3059\u308b\u30b9\u30d7\u30ea\u30f3\u30b0\u306e\u67d4\u8edf\u6027\u3092\u5b9a\u7fa9\u3059\u308b", None))
#endif // QT_CONFIG(tooltip)
        self.label_27.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u30d5\u30ec\u30c3\u30af\u30b9", None))
        self.springExtend_lineEdit.setInputMask("")
        self.springExtend_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"0.0", None))
#if QT_CONFIG(tooltip)
        self.label_32.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>0\u301c1\u306e\u9593\u306b\u8a2d\u5b9a\u3059\u308b</p><p>\u3070\u306d\u306e\u6163\u6027\u3092\u5b9a\u7fa9\u3057\u307e\u3059\u3002\u3053\u308c\u306b\u3088\u308a\u3001\u91cd\u91cf\u7d50\u679c\u304c\u751f\u6210\u3055\u308c\u307e\u3059</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_32.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u6163\u6027", None))
        self.springInertia_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"0.0", None))
#if QT_CONFIG(tooltip)
        self.shelf_button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>Creat shelf button of Spring Magic</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.shelf_button.setText("")
        self.main_tab.setTabText(self.main_tab.indexOf(self.spring_tab), QCoreApplication.translate("SpringMagic_mainWindow", u"\u30b9\u30d7\u30ea\u30f3\u30b0\u30de\u30b8\u30c3\u30af", None))
        self.main_textEdit.setHtml(QCoreApplication.translate("SpringMagic_mainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-size:9pt;\">Created by Bai Yanbin</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'MS Shell Dlg 2'; font-size:9pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'MS Shell Dlg 2'; font-size:9pt;\"><br /></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.link_pushButton.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"\u4f5c\u8005\u7d39\u4ecb", None))
#endif // QT_CONFIG(tooltip)
        self.link_pushButton.setText("")
#if QT_CONFIG(tooltip)
        self.miscUpdate_pushButton.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"\u65b0\u30d0\u30fc\u30b8\u30e7\u30f3\u304c\u5229\u7528\u3067\u304d\u307e\u3059!", None))
#endif // QT_CONFIG(tooltip)
        self.miscUpdate_pushButton.setText("")
#if QT_CONFIG(tooltip)
        self.vimeo_pushButton.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"\u30c1\u30e5\u30fc\u30c8\u30ea\u30a2\u30eb@YouTube", None))
#endif // QT_CONFIG(tooltip)
        self.vimeo_pushButton.setText("")
#if QT_CONFIG(tooltip)
        self.bilibili_pushButton.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"\u30c1\u30e5\u30fc\u30c8\u30ea\u30a2\u30eb@bilibili", None))
#endif // QT_CONFIG(tooltip)
        self.bilibili_pushButton.setText("")

        __sortingEnabled = self.spring_language_list.isSortingEnabled()
        self.spring_language_list.setSortingEnabled(False)
#if QT_CONFIG(tooltip)
        ___qlistwidgetitem = self.spring_language_list.item(0)
#endif
#if QT_CONFIG(tooltip)
        ___qlistwidgetitem.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"\u7b80\u4f53\u4e2d\u6587", None));
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        ___qlistwidgetitem1 = self.spring_language_list.item(1)
#endif
#if QT_CONFIG(tooltip)
        ___qlistwidgetitem1.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"English", None));
#endif // QT_CONFIG(tooltip)
        self.spring_language_list.setSortingEnabled(__sortingEnabled)

#if QT_CONFIG(tooltip)
        self.language_button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"\u8a00\u8a9e\u8a2d\u5b9a", None))
#endif // QT_CONFIG(tooltip)
        self.language_button.setText("")
        pass
    # retranslateUi

