# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'springMagic.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_SpringMagic_mainWindow(object):
    def setupUi(self, SpringMagic_mainWindow):
        if not SpringMagic_mainWindow.objectName():
            SpringMagic_mainWindow.setObjectName(u"SpringMagic_mainWindow")
        SpringMagic_mainWindow.setWindowModality(Qt.NonModal)
        SpringMagic_mainWindow.setEnabled(True)
        SpringMagic_mainWindow.resize(380, 425)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SpringMagic_mainWindow.sizePolicy().hasHeightForWidth())
        SpringMagic_mainWindow.setSizePolicy(sizePolicy)
        SpringMagic_mainWindow.setMinimumSize(QSize(380, 425))
        SpringMagic_mainWindow.setMaximumSize(QSize(380, 655))
        SpringMagic_mainWindow.setCursor(QCursor(Qt.ArrowCursor))
        SpringMagic_mainWindow.setMouseTracking(False)
        SpringMagic_mainWindow.setFocusPolicy(Qt.NoFocus)
        SpringMagic_mainWindow.setWindowTitle(u"Spring Magic 3.5a        Yanbin Bai")
        icon = QIcon()
        icon.addFile(u"icons/Title.png", QSize(), QIcon.Normal, QIcon.Off)
        SpringMagic_mainWindow.setWindowIcon(icon)
        SpringMagic_mainWindow.setIconSize(QSize(24, 24))
        SpringMagic_mainWindow.setToolButtonStyle(Qt.ToolButtonIconOnly)
        SpringMagic_mainWindow.setAnimated(True)
        SpringMagic_mainWindow.setTabShape(QTabWidget.Rounded)
        SpringMagic_mainWindow.setDockNestingEnabled(False)
        self.main_actionReset = QAction(SpringMagic_mainWindow)
        self.main_actionReset.setObjectName(u"main_actionReset")
        self.main_actionReset.setEnabled(False)
        self.main_actionAbout = QAction(SpringMagic_mainWindow)
        self.main_actionAbout.setObjectName(u"main_actionAbout")
        self.main_actionAbout.setCheckable(False)
        self.main_actionAbout.setChecked(False)
        self.main_actionAbout.setEnabled(False)
        self.main_actionAbout.setMenuRole(QAction.AboutRole)
        self.centralwidget = QWidget(SpringMagic_mainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.main_tab = QTabWidget(self.centralwidget)
        self.main_tab.setObjectName(u"main_tab")
        self.main_tab.setEnabled(True)
        self.main_tab.setGeometry(QRect(0, 0, 381, 341))
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.main_tab.sizePolicy().hasHeightForWidth())
        self.main_tab.setSizePolicy(sizePolicy1)
        font = QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.main_tab.setFont(font)
        self.main_tab.setMouseTracking(False)
        self.main_tab.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.main_tab.setAcceptDrops(True)
        self.main_tab.setAutoFillBackground(False)
        self.main_tab.setTabPosition(QTabWidget.North)
        self.main_tab.setTabShape(QTabWidget.Rounded)
        self.main_tab.setElideMode(Qt.ElideNone)
        self.main_tab.setUsesScrollButtons(True)
        self.main_tab.setDocumentMode(False)
        self.main_tab.setTabsClosable(False)
        self.main_tab.setMovable(False)
        self.main_tab.setProperty("tabBarAutoHide", True)
        self.donate_tab = QWidget()
        self.donate_tab.setObjectName(u"donate_tab")
        self.eng_groupBox = QGroupBox(self.donate_tab)
        self.eng_groupBox.setObjectName(u"eng_groupBox")
        self.eng_groupBox.setGeometry(QRect(10, 10, 351, 291))
        font1 = QFont()
        font1.setBold(True)
        font1.setWeight(75)
        self.eng_groupBox.setFont(font1)
        self.eng_groupBox.setFlat(False)
        self.donatePayPal_button = QPushButton(self.eng_groupBox)
        self.donatePayPal_button.setObjectName(u"donatePayPal_button")
        self.donatePayPal_button.setGeometry(QRect(150, 200, 51, 51))
        self.donatePayPal_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon1 = QIcon()
        icon1.addFile(u"icons/paypal.png", QSize(), QIcon.Normal, QIcon.Off)
        self.donatePayPal_button.setIcon(icon1)
        self.donatePayPal_button.setIconSize(QSize(40, 40))
        self.donatePayPal_button.setFlat(True)
        self.label_3 = QLabel(self.eng_groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 160, 121, 121))
        self.label_3.setPixmap(QPixmap(u"icons/ali_pay.png"))
        self.label_21 = QLabel(self.eng_groupBox)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(220, 160, 121, 121))
        self.label_21.setMouseTracking(True)
        self.label_21.setPixmap(QPixmap(u"icons/wechat_pay.png"))
        self.label_22 = QLabel(self.eng_groupBox)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(20, 20, 321, 81))
        self.label = QLabel(self.eng_groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 110, 331, 31))
        font2 = QFont()
        font2.setFamily(u"Microsoft Sans Serif")
        font2.setPointSize(10)
        font2.setBold(False)
        font2.setWeight(50)
        self.label.setFont(font2)
        icon2 = QIcon()
        icon2.addFile(u"icons/donut.png", QSize(), QIcon.Normal, QIcon.Off)
        self.main_tab.addTab(self.donate_tab, icon2, "")
        self.spring_tab = QWidget()
        self.spring_tab.setObjectName(u"spring_tab")
        self.spring_groupBox = QGroupBox(self.spring_tab)
        self.spring_groupBox.setObjectName(u"spring_groupBox")
        self.spring_groupBox.setEnabled(True)
        self.spring_groupBox.setGeometry(QRect(10, -30, 361, 341))
        self.spring_groupBox.setFlat(True)
        self.springSpring_lineEdit = QLineEdit(self.spring_groupBox)
        self.springSpring_lineEdit.setObjectName(u"springSpring_lineEdit")
        self.springSpring_lineEdit.setGeometry(QRect(46, 50, 31, 20))
        self.springSpring_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_24 = QLabel(self.spring_groupBox)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 52, 71, 16))
        self.label_25 = QLabel(self.spring_groupBox)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(160, -68, 31, 16))
        self.springSubs_lineEdit = QLineEdit(self.spring_groupBox)
        self.springSubs_lineEdit.setObjectName(u"springSubs_lineEdit")
        self.springSubs_lineEdit.setGeometry(QRect(190, -70, 31, 20))
        self.label_26 = QLabel(self.spring_groupBox)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(90, 52, 61, 16))
        self.springXspring_lineEdit = QLineEdit(self.spring_groupBox)
        self.springXspring_lineEdit.setObjectName(u"springXspring_lineEdit")
        self.springXspring_lineEdit.setGeometry(QRect(120, 50, 31, 20))
        self.springXspring_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.springBonePose_groupBox = QGroupBox(self.spring_groupBox)
        self.springBonePose_groupBox.setObjectName(u"springBonePose_groupBox")
        self.springBonePose_groupBox.setGeometry(QRect(10, 230, 141, 101))
        self.springBindPose_button = QPushButton(self.springBonePose_groupBox)
        self.springBindPose_button.setObjectName(u"springBindPose_button")
        self.springBindPose_button.setGeometry(QRect(10, 20, 61, 31))
        self.springStraight_button = QPushButton(self.springBonePose_groupBox)
        self.springStraight_button.setObjectName(u"springStraight_button")
        self.springStraight_button.setGeometry(QRect(10, 60, 61, 31))
        font3 = QFont()
        font3.setPointSize(8)
        self.springStraight_button.setFont(font3)
        self.springCopy_button = QPushButton(self.springBonePose_groupBox)
        self.springCopy_button.setObjectName(u"springCopy_button")
        self.springCopy_button.setGeometry(QRect(80, 20, 51, 31))
        self.springPaste_button = QPushButton(self.springBonePose_groupBox)
        self.springPaste_button.setObjectName(u"springPaste_button")
        self.springPaste_button.setGeometry(QRect(80, 60, 51, 31))
        self.springApply_Button = QPushButton(self.spring_groupBox)
        self.springApply_Button.setObjectName(u"springApply_Button")
        self.springApply_Button.setGeometry(QRect(260, 280, 81, 51))
        font4 = QFont()
        font4.setPointSize(10)
        font4.setBold(True)
        font4.setWeight(75)
        self.springApply_Button.setFont(font4)
        self.label_29 = QLabel(self.spring_groupBox)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(420, 40, 41, 16))
        self.collision_groupBox = QGroupBox(self.spring_groupBox)
        self.collision_groupBox.setObjectName(u"collision_groupBox")
        self.collision_groupBox.setGeometry(QRect(10, 160, 331, 61))
        self.springCapsule_checkBox = QCheckBox(self.collision_groupBox)
        self.springCapsule_checkBox.setObjectName(u"springCapsule_checkBox")
        self.springCapsule_checkBox.setGeometry(QRect(10, 30, 61, 17))
        self.springAddBody_Button = QPushButton(self.collision_groupBox)
        self.springAddBody_Button.setObjectName(u"springAddBody_Button")
        self.springAddBody_Button.setEnabled(True)
        self.springAddBody_Button.setGeometry(QRect(180, 14, 41, 41))
        icon3 = QIcon()
        icon3.addFile(u"icons/addCapsule.png", QSize(), QIcon.Normal, QIcon.Off)
        self.springAddBody_Button.setIcon(icon3)
        self.springAddBody_Button.setIconSize(QSize(32, 32))
        self.springAddBody_Button.setCheckable(False)
        self.springAddBody_Button.setFlat(False)
        self.springClearBody_Button = QPushButton(self.collision_groupBox)
        self.springClearBody_Button.setObjectName(u"springClearBody_Button")
        self.springClearBody_Button.setEnabled(True)
        self.springClearBody_Button.setGeometry(QRect(280, 14, 41, 41))
        icon4 = QIcon()
        icon4.addFile(u"icons/clearCapsule.png", QSize(), QIcon.Normal, QIcon.Off)
        self.springClearBody_Button.setIcon(icon4)
        self.springClearBody_Button.setIconSize(QSize(32, 32))
        self.springFastMove_checkBox = QCheckBox(self.collision_groupBox)
        self.springFastMove_checkBox.setObjectName(u"springFastMove_checkBox")
        self.springFastMove_checkBox.setEnabled(False)
        self.springFastMove_checkBox.setGeometry(QRect(80, 30, 75, 17))
        self.springFloor_checkBox = QCheckBox(self.collision_groupBox)
        self.springFloor_checkBox.setObjectName(u"springFloor_checkBox")
        self.springFloor_checkBox.setGeometry(QRect(380, 22, 50, 16))
        self.springFloor_checkBox.setChecked(False)
        self.springFloor_lineEdit = QLineEdit(self.collision_groupBox)
        self.springFloor_lineEdit.setObjectName(u"springFloor_lineEdit")
        self.springFloor_lineEdit.setEnabled(False)
        self.springFloor_lineEdit.setGeometry(QRect(430, 20, 31, 20))
        self.springFloor_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.springAddPlane_Button = QPushButton(self.collision_groupBox)
        self.springAddPlane_Button.setObjectName(u"springAddPlane_Button")
        self.springAddPlane_Button.setEnabled(True)
        self.springAddPlane_Button.setGeometry(QRect(230, 14, 41, 41))
        icon5 = QIcon()
        icon5.addFile(u"icons/addPlane.png", QSize(), QIcon.Normal, QIcon.Off)
        self.springAddPlane_Button.setIcon(icon5)
        self.springAddPlane_Button.setIconSize(QSize(32, 32))
        self.springAddPlane_Button.setCheckable(False)
        self.springAddPlane_Button.setFlat(False)
        self.label_30 = QLabel(self.spring_groupBox)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setEnabled(False)
        self.label_30.setGeometry(QRect(232, 0, 71, 16))
        self.springTension_lineEdit = QLineEdit(self.spring_groupBox)
        self.springTension_lineEdit.setObjectName(u"springTension_lineEdit")
        self.springTension_lineEdit.setEnabled(False)
        self.springTension_lineEdit.setGeometry(QRect(271, 0, 31, 20))
        self.springTension_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.keyRange_groupBox = QGroupBox(self.spring_groupBox)
        self.keyRange_groupBox.setObjectName(u"keyRange_groupBox")
        self.keyRange_groupBox.setGeometry(QRect(10, 80, 331, 71))
        self.springClearSubFrame_checkBox = QCheckBox(self.keyRange_groupBox)
        self.springClearSubFrame_checkBox.setObjectName(u"springClearSubFrame_checkBox")
        self.springClearSubFrame_checkBox.setEnabled(False)
        self.springClearSubFrame_checkBox.setGeometry(QRect(120, 50, 71, 16))
        self.springClearSubFrame_checkBox.setChecked(True)
        self.label_31 = QLabel(self.keyRange_groupBox)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setEnabled(False)
        self.label_31.setGeometry(QRect(20, 50, 71, 16))
        self.springSubDiv_lineEdit = QLineEdit(self.keyRange_groupBox)
        self.springSubDiv_lineEdit.setObjectName(u"springSubDiv_lineEdit")
        self.springSubDiv_lineEdit.setEnabled(False)
        self.springSubDiv_lineEdit.setGeometry(QRect(80, 48, 31, 20))
        self.springSubDiv_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.springActive_radioButton = QRadioButton(self.keyRange_groupBox)
        self.springActive_radioButton.setObjectName(u"springActive_radioButton")
        self.springActive_radioButton.setGeometry(QRect(30, 20, 61, 17))
        self.springActive_radioButton.setChecked(True)
        self.springFrom_radioButton = QRadioButton(self.keyRange_groupBox)
        self.springFrom_radioButton.setObjectName(u"springFrom_radioButton")
        self.springFrom_radioButton.setGeometry(QRect(140, 20, 51, 17))
        self.springFrom_lineEdit = QLineEdit(self.keyRange_groupBox)
        self.springFrom_lineEdit.setObjectName(u"springFrom_lineEdit")
        self.springFrom_lineEdit.setEnabled(False)
        self.springFrom_lineEdit.setGeometry(QRect(190, 20, 31, 20))
        self.springFrom_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_28 = QLabel(self.keyRange_groupBox)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(230, 20, 21, 16))
        self.springEnd_lineEdit = QLineEdit(self.keyRange_groupBox)
        self.springEnd_lineEdit.setObjectName(u"springEnd_lineEdit")
        self.springEnd_lineEdit.setEnabled(False)
        self.springEnd_lineEdit.setGeometry(QRect(250, 20, 31, 20))
        self.springEnd_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.springLoop_checkBox = QCheckBox(self.keyRange_groupBox)
        self.springLoop_checkBox.setObjectName(u"springLoop_checkBox")
        self.springLoop_checkBox.setGeometry(QRect(280, 50, 51, 16))
        self.springLoop_checkBox.setChecked(False)
        self.springPoseMatch_checkBox = QCheckBox(self.keyRange_groupBox)
        self.springPoseMatch_checkBox.setObjectName(u"springPoseMatch_checkBox")
        self.springPoseMatch_checkBox.setEnabled(True)
        self.springPoseMatch_checkBox.setGeometry(QRect(194, 50, 81, 16))
        self.springPoseMatch_checkBox.setFont(font3)
        self.springPoseMatch_checkBox.setCheckable(True)
        self.springPoseMatch_checkBox.setChecked(False)
        self.springWind_Button = QPushButton(self.spring_groupBox)
        self.springWind_Button.setObjectName(u"springWind_Button")
        self.springWind_Button.setGeometry(QRect(260, 240, 81, 31))
        self.springWind_Button.setFont(font)
        icon6 = QIcon()
        icon6.addFile(u"icons/wind.png", QSize(), QIcon.Normal, QIcon.Off)
        self.springWind_Button.setIcon(icon6)
        self.springWind_Button.setIconSize(QSize(24, 24))
        self.ctrl_groupBox = QGroupBox(self.spring_groupBox)
        self.ctrl_groupBox.setObjectName(u"ctrl_groupBox")
        self.ctrl_groupBox.setGeometry(QRect(160, 230, 91, 101))
        self.springBind_Button = QPushButton(self.ctrl_groupBox)
        self.springBind_Button.setObjectName(u"springBind_Button")
        self.springBind_Button.setGeometry(QRect(10, 20, 71, 31))
        self.springBind_Button.setFont(font)
        icon7 = QIcon()
        icon7.addFile(u"icons/ctrl_bind.png", QSize(), QIcon.Normal, QIcon.Off)
        self.springBind_Button.setIcon(icon7)
        self.springBind_Button.setIconSize(QSize(24, 24))
        self.springBake_Button = QPushButton(self.ctrl_groupBox)
        self.springBake_Button.setObjectName(u"springBake_Button")
        self.springBake_Button.setEnabled(True)
        self.springBake_Button.setGeometry(QRect(10, 60, 71, 31))
        icon8 = QIcon()
        icon8.addFile(u"icons/ctrl_bake.png", QSize(), QIcon.Normal, QIcon.Off)
        self.springBake_Button.setIcon(icon8)
        self.springBake_Button.setIconSize(QSize(24, 24))
        self.label_27 = QLabel(self.spring_groupBox)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(166, 52, 61, 16))
        self.springExtend_lineEdit = QLineEdit(self.spring_groupBox)
        self.springExtend_lineEdit.setObjectName(u"springExtend_lineEdit")
        self.springExtend_lineEdit.setGeometry(QRect(192, 50, 31, 20))
        self.springExtend_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_32 = QLabel(self.spring_groupBox)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(240, 52, 61, 16))
        self.label_32.setFont(font3)
        self.springInertia_lineEdit = QLineEdit(self.spring_groupBox)
        self.springInertia_lineEdit.setObjectName(u"springInertia_lineEdit")
        self.springInertia_lineEdit.setGeometry(QRect(277, 50, 31, 20))
        self.springInertia_lineEdit.setFont(font3)
        self.springInertia_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.shelf_button = QPushButton(self.spring_groupBox)
        self.shelf_button.setObjectName(u"shelf_button")
        self.shelf_button.setGeometry(QRect(320, 40, 30, 30))
        sizePolicy2 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.shelf_button.sizePolicy().hasHeightForWidth())
        self.shelf_button.setSizePolicy(sizePolicy2)
        self.shelf_button.setLayoutDirection(Qt.LeftToRight)
        self.shelf_button.setAutoFillBackground(False)
        icon9 = QIcon()
        icon9.addFile(u"icons/Shelf.png", QSize(), QIcon.Normal, QIcon.Off)
        self.shelf_button.setIcon(icon9)
        self.shelf_button.setIconSize(QSize(30, 30))
        self.shelf_button.setCheckable(False)
        self.shelf_button.setAutoRepeat(False)
        self.shelf_button.setAutoExclusive(False)
        self.shelf_button.setFlat(True)
        self.label_24.raise_()
        self.keyRange_groupBox.raise_()
        self.springSpring_lineEdit.raise_()
        self.label_25.raise_()
        self.springSubs_lineEdit.raise_()
        self.label_26.raise_()
        self.springXspring_lineEdit.raise_()
        self.springBonePose_groupBox.raise_()
        self.springApply_Button.raise_()
        self.label_29.raise_()
        self.collision_groupBox.raise_()
        self.label_30.raise_()
        self.springTension_lineEdit.raise_()
        self.springWind_Button.raise_()
        self.ctrl_groupBox.raise_()
        self.label_27.raise_()
        self.springExtend_lineEdit.raise_()
        self.label_32.raise_()
        self.springInertia_lineEdit.raise_()
        self.shelf_button.raise_()
        icon10 = QIcon()
        icon10.addFile(u"icons/spring.png", QSize(), QIcon.Normal, QIcon.Off)
        self.main_tab.addTab(self.spring_tab, icon10, "")
        self.main_textEdit = QTextEdit(self.centralwidget)
        self.main_textEdit.setObjectName(u"main_textEdit")
        self.main_textEdit.setGeometry(QRect(10, 410, 345, 200))
        sizePolicy3 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy3.setHorizontalStretch(200)
        sizePolicy3.setVerticalStretch(200)
        sizePolicy3.setHeightForWidth(self.main_textEdit.sizePolicy().hasHeightForWidth())
        self.main_textEdit.setSizePolicy(sizePolicy3)
        self.main_textEdit.setMinimumSize(QSize(345, 40))
        self.main_textEdit.setMaximumSize(QSize(345, 200))
        self.main_textEdit.setFont(font3)
        self.main_textEdit.setReadOnly(True)
        self.main_progressBar = QProgressBar(self.centralwidget)
        self.main_progressBar.setObjectName(u"main_progressBar")
        self.main_progressBar.setGeometry(QRect(10, 375, 361, 27))
        font5 = QFont()
        font5.setFamily(u"Consolas")
        font5.setPointSize(12)
        self.main_progressBar.setFont(font5)
        self.main_progressBar.setAcceptDrops(False)
        self.main_progressBar.setValue(0)
        self.main_progressBar.setAlignment(Qt.AlignCenter)
        self.main_progressBar.setTextVisible(True)
        self.main_progressBar.setOrientation(Qt.Horizontal)
        self.main_progressBar.setInvertedAppearance(False)
        self.main_progressBar.setTextDirection(QProgressBar.TopToBottom)
        self.main_processLabel = QLabel(self.centralwidget)
        self.main_processLabel.setObjectName(u"main_processLabel")
        self.main_processLabel.setGeometry(QRect(13, 353, 231, 16))
        self.main_processLabel.setFont(font3)
        self.main_processLabel.setText(u"")
        self.main_processLabel.setTextFormat(Qt.PlainText)
        self.main_processLabel.setTextInteractionFlags(Qt.LinksAccessibleByMouse|Qt.TextSelectableByMouse)
        self.link_pushButton = QPushButton(self.centralwidget)
        self.link_pushButton.setObjectName(u"link_pushButton")
        self.link_pushButton.setEnabled(True)
        self.link_pushButton.setGeometry(QRect(340, 342, 31, 31))
        font6 = QFont()
        font6.setUnderline(False)
        self.link_pushButton.setFont(font6)
        self.link_pushButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.link_pushButton.setMouseTracking(False)
        self.link_pushButton.setFocusPolicy(Qt.NoFocus)
        self.link_pushButton.setAutoFillBackground(False)
        icon11 = QIcon()
        icon11.addFile(u"icons/linkedin.png", QSize(), QIcon.Normal, QIcon.Off)
        self.link_pushButton.setIcon(icon11)
        self.link_pushButton.setIconSize(QSize(25, 25))
        self.link_pushButton.setCheckable(False)
        self.link_pushButton.setChecked(False)
        self.link_pushButton.setAutoDefault(False)
        self.link_pushButton.setFlat(True)
        self.miscUpdate_pushButton = QPushButton(self.centralwidget)
        self.miscUpdate_pushButton.setObjectName(u"miscUpdate_pushButton")
        self.miscUpdate_pushButton.setGeometry(QRect(220, 342, 31, 30))
        sizePolicy2.setHeightForWidth(self.miscUpdate_pushButton.sizePolicy().hasHeightForWidth())
        self.miscUpdate_pushButton.setSizePolicy(sizePolicy2)
        self.miscUpdate_pushButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.miscUpdate_pushButton.setLayoutDirection(Qt.LeftToRight)
        self.miscUpdate_pushButton.setAutoFillBackground(False)
        icon12 = QIcon()
        icon12.addFile(u"icons/update.png", QSize(), QIcon.Normal, QIcon.Off)
        self.miscUpdate_pushButton.setIcon(icon12)
        self.miscUpdate_pushButton.setIconSize(QSize(25, 25))
        self.miscUpdate_pushButton.setCheckable(False)
        self.miscUpdate_pushButton.setAutoRepeat(False)
        self.miscUpdate_pushButton.setAutoExclusive(False)
        self.miscUpdate_pushButton.setFlat(True)
        self.vimeo_pushButton = QPushButton(self.centralwidget)
        self.vimeo_pushButton.setObjectName(u"vimeo_pushButton")
        self.vimeo_pushButton.setEnabled(True)
        self.vimeo_pushButton.setGeometry(QRect(280, 342, 31, 31))
        self.vimeo_pushButton.setFont(font6)
        self.vimeo_pushButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.vimeo_pushButton.setMouseTracking(False)
        self.vimeo_pushButton.setFocusPolicy(Qt.NoFocus)
        self.vimeo_pushButton.setAutoFillBackground(False)
        icon13 = QIcon()
        icon13.addFile(u"icons/youtube.png", QSize(), QIcon.Normal, QIcon.Off)
        self.vimeo_pushButton.setIcon(icon13)
        self.vimeo_pushButton.setIconSize(QSize(25, 25))
        self.vimeo_pushButton.setCheckable(False)
        self.vimeo_pushButton.setChecked(False)
        self.vimeo_pushButton.setAutoDefault(False)
        self.vimeo_pushButton.setFlat(True)
        self.bilibili_pushButton = QPushButton(self.centralwidget)
        self.bilibili_pushButton.setObjectName(u"bilibili_pushButton")
        self.bilibili_pushButton.setEnabled(True)
        self.bilibili_pushButton.setGeometry(QRect(250, 342, 31, 31))
        self.bilibili_pushButton.setFont(font6)
        self.bilibili_pushButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.bilibili_pushButton.setMouseTracking(False)
        self.bilibili_pushButton.setFocusPolicy(Qt.NoFocus)
        self.bilibili_pushButton.setAutoFillBackground(False)
        icon14 = QIcon()
        icon14.addFile(u"icons/bilibili.png", QSize(), QIcon.Normal, QIcon.Off)
        self.bilibili_pushButton.setIcon(icon14)
        self.bilibili_pushButton.setIconSize(QSize(25, 25))
        self.bilibili_pushButton.setCheckable(False)
        self.bilibili_pushButton.setChecked(False)
        self.bilibili_pushButton.setAutoDefault(False)
        self.bilibili_pushButton.setFlat(True)
        self.language_button = QPushButton(self.centralwidget)
        self.language_button.setObjectName(u"language_button")
        self.language_button.setEnabled(True)
        self.language_button.setGeometry(QRect(310, 342, 31, 31))
        self.language_button.setFont(font6)
        self.language_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.language_button.setMouseTracking(False)
        self.language_button.setFocusPolicy(Qt.NoFocus)
        self.language_button.setAutoFillBackground(False)
        icon15 = QIcon()
        icon15.addFile(u"icons/language.png", QSize(), QIcon.Normal, QIcon.Off)
        self.language_button.setIcon(icon15)
        self.language_button.setIconSize(QSize(25, 25))
        self.language_button.setCheckable(False)
        self.language_button.setChecked(False)
        self.language_button.setAutoDefault(False)
        self.language_button.setFlat(True)
        self.main_lang_id = QLabel(self.centralwidget)
        self.main_lang_id.setObjectName(u"main_lang_id")
        self.main_lang_id.setGeometry(QRect(-50, 360, 21, 16))
        self.main_lang_id.setFont(font3)
        self.main_lang_id.setText(u"eng")
        self.spring_language_list = QListWidget(self.centralwidget)
        icon16 = QIcon()
        icon16.addFile(u"icons/China Flag.png", QSize(), QIcon.Normal, QIcon.Off)
        __qlistwidgetitem = QListWidgetItem(self.spring_language_list)
        __qlistwidgetitem.setTextAlignment(Qt.AlignHCenter|Qt.AlignVCenter|Qt.AlignCenter);
        __qlistwidgetitem.setIcon(icon16);
        __qlistwidgetitem.setFlags(Qt.ItemIsSelectable|Qt.ItemIsEnabled);
        icon17 = QIcon()
        icon17.addFile(u"icons/english.png", QSize(), QIcon.Normal, QIcon.Off)
        __qlistwidgetitem1 = QListWidgetItem(self.spring_language_list)
        __qlistwidgetitem1.setTextAlignment(Qt.AlignHCenter|Qt.AlignVCenter|Qt.AlignCenter);
        __qlistwidgetitem1.setIcon(icon17);
        __qlistwidgetitem1.setFlags(Qt.ItemIsSelectable|Qt.ItemIsEnabled);
        icon18 = QIcon()
        icon18.addFile(u"icons/japanese.png", QSize(), QIcon.Normal, QIcon.Off)
        __qlistwidgetitem2 = QListWidgetItem(self.spring_language_list)
        __qlistwidgetitem2.setTextAlignment(Qt.AlignHCenter|Qt.AlignVCenter|Qt.AlignCenter);
        __qlistwidgetitem2.setIcon(icon18);
        __qlistwidgetitem2.setFlags(Qt.ItemIsSelectable|Qt.ItemIsEnabled);
        self.spring_language_list.setObjectName(u"spring_language_list")
        self.spring_language_list.setGeometry(QRect(307, 235, 36, 111))
        font7 = QFont()
        font7.setKerning(False)
        self.spring_language_list.setFont(font7)
        self.spring_language_list.setAutoFillBackground(False)
        self.spring_language_list.setFrameShape(QFrame.NoFrame)
        self.spring_language_list.setFrameShadow(QFrame.Raised)
        self.spring_language_list.setLineWidth(0)
        self.spring_language_list.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.spring_language_list.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.spring_language_list.setFlow(QListView.LeftToRight)
        self.spring_language_list.setGridSize(QSize(36, 36))
        self.spring_language_list.setViewMode(QListView.IconMode)
        SpringMagic_mainWindow.setCentralWidget(self.centralwidget)
        self.main_processLabel.raise_()
        self.link_pushButton.raise_()
        self.main_tab.raise_()
        self.main_textEdit.raise_()
        self.main_progressBar.raise_()
        self.miscUpdate_pushButton.raise_()
        self.vimeo_pushButton.raise_()
        self.bilibili_pushButton.raise_()
        self.language_button.raise_()
        self.main_lang_id.raise_()
        self.spring_language_list.raise_()
        self.statusbar = QStatusBar(SpringMagic_mainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setEnabled(True)
        SpringMagic_mainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.main_tab, self.main_textEdit)

        self.retranslateUi(SpringMagic_mainWindow)
        self.springCapsule_checkBox.clicked.connect(self.springFastMove_checkBox.setEnabled)
        self.springCapsule_checkBox.clicked.connect(self.label_31.setEnabled)
        self.springCapsule_checkBox.clicked.connect(self.springSubDiv_lineEdit.setEnabled)
        self.springCapsule_checkBox.clicked.connect(self.label_30.setEnabled)
        self.springCapsule_checkBox.clicked.connect(self.springTension_lineEdit.setEnabled)
        self.springFrom_radioButton.toggled.connect(self.springFrom_lineEdit.setEnabled)
        self.springFrom_radioButton.toggled.connect(self.springEnd_lineEdit.setEnabled)
        self.springCapsule_checkBox.clicked.connect(self.springClearSubFrame_checkBox.setEnabled)

        self.main_tab.setCurrentIndex(1)
        self.link_pushButton.setDefault(False)
        self.vimeo_pushButton.setDefault(False)
        self.bilibili_pushButton.setDefault(False)
        self.language_button.setDefault(False)


        QMetaObject.connectSlotsByName(SpringMagic_mainWindow)
    # setupUi

    def retranslateUi(self, SpringMagic_mainWindow):
        self.main_actionReset.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Reset", None))
        self.main_actionAbout.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"About...", None))
#if QT_CONFIG(tooltip)
        self.main_tab.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.main_tab.setStatusTip("")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.main_tab.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.main_tab.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.main_tab.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.eng_groupBox.setTitle(QCoreApplication.translate("SpringMagic_mainWindow", u"Need Your Supports! ", None))
#if QT_CONFIG(tooltip)
        self.donatePayPal_button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>PayPal Link</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.donatePayPal_button.setText("")
#if QT_CONFIG(tooltip)
        self.label_3.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>AliPay QR Code</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_3.setText("")
#if QT_CONFIG(tooltip)
        self.label_21.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>WeChat Pay QR Code</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_21.setText("")
        self.label_22.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:8pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-weight:400;\">Spring Magic is free for everyone, you can use</span><span style=\" font-family:'MS Shell Dlg 2';\"> Full Function</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-weight:400;\"> as free! However if this make your life easier...</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-"
                        "indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-size:10pt;\">How about bought me cup of coffee?</span></p></body></html>", None))
        self.label.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p><span style=\" font-size:8pt;\">Special Thanks\uff1a</span><span style=\" font-size:8pt; font-weight:600;\">Benoit Degand</span><span style=\" font-size:8pt;\"> help improve performance</span></p></body></html>", None))
        self.main_tab.setTabText(self.main_tab.indexOf(self.donate_tab), QCoreApplication.translate("SpringMagic_mainWindow", u"Donate", None))
        self.spring_groupBox.setTitle(QCoreApplication.translate("SpringMagic_mainWindow", u" Spring Magic ", None))
        self.springSpring_lineEdit.setInputMask("")
        self.springSpring_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"0.7", None))
#if QT_CONFIG(tooltip)
        self.label_24.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>set between 0 to 1</p><p>define how soft the spring is, bigger value, softer result.</p><p>Important: only working for &quot;X-axis aiming to child&quot; joint chain.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_24.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Spring", None))
        self.label_25.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Subs", None))
        self.springSubs_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"0", None))
#if QT_CONFIG(tooltip)
        self.label_26.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>set between 0 to 1</p><p>define how soft the twist (X-axis) is</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_26.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Twist", None))
        self.springXspring_lineEdit.setInputMask("")
        self.springXspring_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"0.7", None))
        self.springBonePose_groupBox.setTitle(QCoreApplication.translate("SpringMagic_mainWindow", u" Bone Pose ", None))
#if QT_CONFIG(tooltip)
        self.springBindPose_button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"Go to joint bind pose", None))
#endif // QT_CONFIG(tooltip)
        self.springBindPose_button.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Bind Pose", None))
#if QT_CONFIG(tooltip)
        self.springStraight_button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"Set joint chain as straight", None))
#endif // QT_CONFIG(tooltip)
        self.springStraight_button.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Straight", None))
#if QT_CONFIG(tooltip)
        self.springCopy_button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"Copy bone poses", None))
#endif // QT_CONFIG(tooltip)
        self.springCopy_button.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Copy", None))
#if QT_CONFIG(tooltip)
        self.springPaste_button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"Paste bone poses", None))
#endif // QT_CONFIG(tooltip)
        self.springPaste_button.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Paste", None))
#if QT_CONFIG(tooltip)
        self.springApply_Button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>Affect select object only</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springApply_Button.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Apply", None))
        self.label_29.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"UpAxis", None))
        self.collision_groupBox.setTitle(QCoreApplication.translate("SpringMagic_mainWindow", u" Collisions ", None))
#if QT_CONFIG(tooltip)
        self.springCapsule_checkBox.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>Active collision calculation with capsule body in scene.</p><p>May slow down the calculation</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springCapsule_checkBox.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Active", None))
#if QT_CONFIG(tooltip)
        self.springAddBody_Button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>Add a capsule at original point if select notion, or add a capsule match with selected bone.</p><p>Note: you can adjust the capsule with move or scale the cylinder at middle. Parent capsule to diffecrent object to move follow it.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springAddBody_Button.setText("")
#if QT_CONFIG(tooltip)
        self.springClearBody_Button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>Clear all capsules in scene</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springClearBody_Button.setText("")
#if QT_CONFIG(tooltip)
        self.springFastMove_checkBox.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>Click on this if capsule attach on a fast move bone, like sprinting legs, to reduce the clip through.</p><p>Note: May cause more poping if capsule moving slowly.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springFastMove_checkBox.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Fast Move", None))
#if QT_CONFIG(tooltip)
        self.springFloor_checkBox.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>Add a floor collition for joint chain</p><p>Script will trying to keep all the joints above the hight during caculation</p><p>\u542f\u7528\u5730\u9762\u78b0\u649e\uff0c\u8ba1\u7b97\u65f6\u4f1a\u5c3d\u91cf\u5c06\u9aa8\u9abc\u4fdd\u6301\u5728\u8bbe\u5b9a\u9ad8\u5ea6\u4e4b\u4e0a</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springFloor_checkBox.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Floor", None))
#if QT_CONFIG(tooltip)
        self.springFloor_lineEdit.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>Floor height</p><p>\u5730\u9762\u9ad8\u5ea6</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springFloor_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"0.0", None))
#if QT_CONFIG(tooltip)
        self.springAddPlane_Button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>Create a collision plane</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springAddPlane_Button.setText("")
#if QT_CONFIG(tooltip)
        self.label_30.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>Tension of the chain, means how much the force of bend will be path through the chain, only take effect when collision happends. Can reduce poping and clip through of collision result.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_30.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Tension", None))
        self.springTension_lineEdit.setInputMask("")
        self.springTension_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"0.5", None))
        self.keyRange_groupBox.setTitle(QCoreApplication.translate("SpringMagic_mainWindow", u"Key Setting", None))
#if QT_CONFIG(tooltip)
        self.springClearSubFrame_checkBox.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>Remove precision keys on sub frame after calculation</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springClearSubFrame_checkBox.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Wipe Sub", None))
#if QT_CONFIG(tooltip)
        self.label_31.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>How many sub frame that will be go through during 1 frame, that for capture really fast move</p><p>collision body. Default value is 1, if set as 5, means will step as 1/5 frame to calculation.</p><p>will increase calculation time by times</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_31.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Sub-Frame", None))
        self.springSubDiv_lineEdit.setInputMask("")
        self.springSubDiv_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"1", None))
#if QT_CONFIG(tooltip)
        self.springActive_radioButton.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"Current time line range", None))
#endif // QT_CONFIG(tooltip)
        self.springActive_radioButton.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Active", None))
        self.springFrom_radioButton.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"From", None))
        self.springFrom_lineEdit.setInputMask("")
        self.springFrom_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"0", None))
        self.label_28.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"To", None))
        self.springEnd_lineEdit.setInputMask("")
        self.springEnd_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"200", None))
#if QT_CONFIG(tooltip)
        self.springLoop_checkBox.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>Will caculate twice to get looped result</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springLoop_checkBox.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Loop", None))
#if QT_CONFIG(tooltip)
        self.springPoseMatch_checkBox.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>make result close to exists keyframe pose</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springPoseMatch_checkBox.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Pose Match", None))
#if QT_CONFIG(tooltip)
        self.springWind_Button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>Add wind controller</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springWind_Button.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Wind", None))
        self.ctrl_groupBox.setTitle(QCoreApplication.translate("SpringMagic_mainWindow", u"Controller", None))
#if QT_CONFIG(tooltip)
        self.springBind_Button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>Bind bone chain to selected rigging controller</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springBind_Button.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Bind", None))
#if QT_CONFIG(tooltip)
        self.springBake_Button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>Bake bone chain animation back to controller</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springBake_Button.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Bake", None))
#if QT_CONFIG(tooltip)
        self.label_27.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>set between 0 to 1</p><p>define flexibility of spring, which can produce strech and squash animation</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_27.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Flex", None))
        self.springExtend_lineEdit.setInputMask("")
        self.springExtend_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"0.0", None))
#if QT_CONFIG(tooltip)
        self.label_32.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>set between 0 to 1</p><p>define inertia of spring, which can produce weight result</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_32.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Inertia", None))
        self.springInertia_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"0.0", None))
#if QT_CONFIG(tooltip)
        self.shelf_button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>Creat shelf button of Spring Magic</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.shelf_button.setText("")
        self.main_tab.setTabText(self.main_tab.indexOf(self.spring_tab), QCoreApplication.translate("SpringMagic_mainWindow", u"Spring Magic", None))
        self.main_textEdit.setHtml(QCoreApplication.translate("SpringMagic_mainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-size:9pt;\">Created by Bai Yanbin</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'MS Shell Dlg 2'; font-size:9pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'MS Shell Dlg 2'; font-size:9pt;\"><br /></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.link_pushButton.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"Author Profile", None))
#endif // QT_CONFIG(tooltip)
        self.link_pushButton.setText("")
#if QT_CONFIG(tooltip)
        self.miscUpdate_pushButton.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"New Version Available!", None))
#endif // QT_CONFIG(tooltip)
        self.miscUpdate_pushButton.setText("")
#if QT_CONFIG(tooltip)
        self.vimeo_pushButton.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"Tutorials on YouTube", None))
#endif // QT_CONFIG(tooltip)
        self.vimeo_pushButton.setText("")
#if QT_CONFIG(tooltip)
        self.bilibili_pushButton.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"Tutorials on bilibili", None))
#endif // QT_CONFIG(tooltip)
        self.bilibili_pushButton.setText("")
#if QT_CONFIG(tooltip)
        self.language_button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"Set Language", None))
#endif // QT_CONFIG(tooltip)
        self.language_button.setText("")

        __sortingEnabled = self.spring_language_list.isSortingEnabled()
        self.spring_language_list.setSortingEnabled(False)
#if QT_CONFIG(tooltip)
        ___qlistwidgetitem = self.spring_language_list.item(0)
#endif
#if QT_CONFIG(tooltip)
        ___qlistwidgetitem.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"\u7b80\u4f53\u4e2d\u6587", None));
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        ___qlistwidgetitem1 = self.spring_language_list.item(1)
#endif
#if QT_CONFIG(tooltip)
        ___qlistwidgetitem1.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"English", None));
#endif // QT_CONFIG(tooltip)
        self.spring_language_list.setSortingEnabled(__sortingEnabled)

        pass
    # retranslateUi

