# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'springMagic_chn.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_SpringMagic_mainWindow(object):
    def setupUi(self, SpringMagic_mainWindow):
        if not SpringMagic_mainWindow.objectName():
            SpringMagic_mainWindow.setObjectName(u"SpringMagic_mainWindow")
        SpringMagic_mainWindow.setWindowModality(Qt.NonModal)
        SpringMagic_mainWindow.setEnabled(True)
        SpringMagic_mainWindow.resize(380, 425)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SpringMagic_mainWindow.sizePolicy().hasHeightForWidth())
        SpringMagic_mainWindow.setSizePolicy(sizePolicy)
        SpringMagic_mainWindow.setMinimumSize(QSize(380, 425))
        SpringMagic_mainWindow.setMaximumSize(QSize(380, 655))
        SpringMagic_mainWindow.setCursor(QCursor(Qt.ArrowCursor))
        SpringMagic_mainWindow.setMouseTracking(False)
        SpringMagic_mainWindow.setFocusPolicy(Qt.NoFocus)
        SpringMagic_mainWindow.setWindowTitle(u"Spring Magic 3.5a          \u767d\u4e25\u5bbe")
        icon = QIcon()
        icon.addFile(u"icons/Title.png", QSize(), QIcon.Normal, QIcon.Off)
        SpringMagic_mainWindow.setWindowIcon(icon)
        SpringMagic_mainWindow.setIconSize(QSize(24, 24))
        SpringMagic_mainWindow.setToolButtonStyle(Qt.ToolButtonIconOnly)
        SpringMagic_mainWindow.setAnimated(True)
        SpringMagic_mainWindow.setTabShape(QTabWidget.Rounded)
        SpringMagic_mainWindow.setDockNestingEnabled(False)
        self.main_actionReset = QAction(SpringMagic_mainWindow)
        self.main_actionReset.setObjectName(u"main_actionReset")
        self.main_actionReset.setEnabled(False)
        self.main_actionAbout = QAction(SpringMagic_mainWindow)
        self.main_actionAbout.setObjectName(u"main_actionAbout")
        self.main_actionAbout.setCheckable(False)
        self.main_actionAbout.setChecked(False)
        self.main_actionAbout.setEnabled(False)
        self.main_actionAbout.setMenuRole(QAction.AboutRole)
        self.centralwidget = QWidget(SpringMagic_mainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.main_tab = QTabWidget(self.centralwidget)
        self.main_tab.setObjectName(u"main_tab")
        self.main_tab.setEnabled(True)
        self.main_tab.setGeometry(QRect(0, 0, 381, 341))
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.main_tab.sizePolicy().hasHeightForWidth())
        self.main_tab.setSizePolicy(sizePolicy1)
        font = QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QFont.PreferDefault)
        self.main_tab.setFont(font)
        self.main_tab.setMouseTracking(False)
        self.main_tab.setTabPosition(QTabWidget.North)
        self.main_tab.setTabShape(QTabWidget.Rounded)
        self.main_tab.setElideMode(Qt.ElideNone)
        self.main_tab.setUsesScrollButtons(True)
        self.main_tab.setDocumentMode(False)
        self.main_tab.setTabsClosable(False)
        self.main_tab.setMovable(False)
        self.donate_tab = QWidget()
        self.donate_tab.setObjectName(u"donate_tab")
        self.eng_groupBox = QGroupBox(self.donate_tab)
        self.eng_groupBox.setObjectName(u"eng_groupBox")
        self.eng_groupBox.setGeometry(QRect(10, 10, 351, 291))
        font1 = QFont()
        font1.setBold(True)
        font1.setWeight(75)
        self.eng_groupBox.setFont(font1)
        self.eng_groupBox.setFlat(False)
        self.donatePayPal_button = QPushButton(self.eng_groupBox)
        self.donatePayPal_button.setObjectName(u"donatePayPal_button")
        self.donatePayPal_button.setGeometry(QRect(150, 200, 51, 51))
        self.donatePayPal_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon1 = QIcon()
        icon1.addFile(u"icons/paypal.png", QSize(), QIcon.Normal, QIcon.Off)
        self.donatePayPal_button.setIcon(icon1)
        self.donatePayPal_button.setIconSize(QSize(40, 40))
        self.donatePayPal_button.setFlat(True)
        self.label_3 = QLabel(self.eng_groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 160, 121, 121))
        self.label_3.setPixmap(QPixmap(u"icons/ali_pay.png"))
        self.label_21 = QLabel(self.eng_groupBox)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(220, 160, 121, 121))
        self.label_21.setMouseTracking(True)
        self.label_21.setPixmap(QPixmap(u"icons/wechat_pay.png"))
        self.label_22 = QLabel(self.eng_groupBox)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(20, 20, 321, 81))
        self.label = QLabel(self.eng_groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 112, 321, 31))
        font2 = QFont()
        font2.setPointSize(10)
        self.label.setFont(font2)
        icon2 = QIcon()
        icon2.addFile(u"icons/donut.png", QSize(), QIcon.Normal, QIcon.Off)
        self.main_tab.addTab(self.donate_tab, icon2, "")
        self.spring_tab = QWidget()
        self.spring_tab.setObjectName(u"spring_tab")
        self.spring_groupBox = QGroupBox(self.spring_tab)
        self.spring_groupBox.setObjectName(u"spring_groupBox")
        self.spring_groupBox.setEnabled(True)
        self.spring_groupBox.setGeometry(QRect(20, -20, 341, 341))
        self.spring_groupBox.setFont(font2)
        self.spring_groupBox.setFlat(True)
        self.springSpring_lineEdit = QLineEdit(self.spring_groupBox)
        self.springSpring_lineEdit.setObjectName(u"springSpring_lineEdit")
        self.springSpring_lineEdit.setGeometry(QRect(40, 40, 31, 20))
        self.springSpring_lineEdit.setFont(font2)
        self.springSpring_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_15 = QLabel(self.spring_groupBox)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 42, 61, 16))
        self.label_15.setFont(font2)
        self.label_16 = QLabel(self.spring_groupBox)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(160, -68, 31, 16))
        self.label_16.setFont(font2)
        self.springSubs_lineEdit = QLineEdit(self.spring_groupBox)
        self.springSubs_lineEdit.setObjectName(u"springSubs_lineEdit")
        self.springSubs_lineEdit.setGeometry(QRect(190, -70, 31, 20))
        self.springSubs_lineEdit.setFont(font2)
        self.label_17 = QLabel(self.spring_groupBox)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(86, 42, 61, 16))
        self.label_17.setFont(font2)
        self.springXspring_lineEdit = QLineEdit(self.spring_groupBox)
        self.springXspring_lineEdit.setObjectName(u"springXspring_lineEdit")
        self.springXspring_lineEdit.setGeometry(QRect(116, 40, 31, 20))
        self.springXspring_lineEdit.setFont(font2)
        self.springXspring_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.springBonePose_groupBox = QGroupBox(self.spring_groupBox)
        self.springBonePose_groupBox.setObjectName(u"springBonePose_groupBox")
        self.springBonePose_groupBox.setGeometry(QRect(0, 220, 141, 101))
        self.springBonePose_groupBox.setFont(font2)
        self.springBindPose_button = QPushButton(self.springBonePose_groupBox)
        self.springBindPose_button.setObjectName(u"springBindPose_button")
        self.springBindPose_button.setGeometry(QRect(10, 20, 61, 31))
        self.springBindPose_button.setFont(font2)
        self.springStraight_button = QPushButton(self.springBonePose_groupBox)
        self.springStraight_button.setObjectName(u"springStraight_button")
        self.springStraight_button.setGeometry(QRect(10, 60, 61, 31))
        self.springStraight_button.setFont(font2)
        self.springCopy_button = QPushButton(self.springBonePose_groupBox)
        self.springCopy_button.setObjectName(u"springCopy_button")
        self.springCopy_button.setGeometry(QRect(80, 20, 51, 31))
        self.springCopy_button.setFont(font2)
        self.springPaste_button = QPushButton(self.springBonePose_groupBox)
        self.springPaste_button.setObjectName(u"springPaste_button")
        self.springPaste_button.setGeometry(QRect(80, 60, 51, 31))
        self.springPaste_button.setFont(font2)
        self.springApply_Button = QPushButton(self.spring_groupBox)
        self.springApply_Button.setObjectName(u"springApply_Button")
        self.springApply_Button.setGeometry(QRect(250, 270, 81, 51))
        font3 = QFont()
        font3.setPointSize(12)
        font3.setBold(True)
        font3.setWeight(75)
        self.springApply_Button.setFont(font3)
        self.label_8 = QLabel(self.spring_groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(350, 22, 41, 16))
        self.label_8.setFont(font2)
        self.collision_groupBox = QGroupBox(self.spring_groupBox)
        self.collision_groupBox.setObjectName(u"collision_groupBox")
        self.collision_groupBox.setGeometry(QRect(0, 150, 331, 61))
        self.collision_groupBox.setFont(font2)
        self.springCapsule_checkBox = QCheckBox(self.collision_groupBox)
        self.springCapsule_checkBox.setObjectName(u"springCapsule_checkBox")
        self.springCapsule_checkBox.setGeometry(QRect(10, 30, 51, 17))
        self.springCapsule_checkBox.setFont(font2)
        self.springFastMove_checkBox = QCheckBox(self.collision_groupBox)
        self.springFastMove_checkBox.setObjectName(u"springFastMove_checkBox")
        self.springFastMove_checkBox.setEnabled(False)
        self.springFastMove_checkBox.setGeometry(QRect(70, 30, 71, 17))
        self.springFastMove_checkBox.setFont(font2)
        self.springFloor_checkBox = QCheckBox(self.collision_groupBox)
        self.springFloor_checkBox.setObjectName(u"springFloor_checkBox")
        self.springFloor_checkBox.setGeometry(QRect(380, 22, 50, 16))
        self.springFloor_checkBox.setFont(font2)
        self.springFloor_checkBox.setChecked(False)
        self.springFloor_lineEdit = QLineEdit(self.collision_groupBox)
        self.springFloor_lineEdit.setObjectName(u"springFloor_lineEdit")
        self.springFloor_lineEdit.setEnabled(False)
        self.springFloor_lineEdit.setGeometry(QRect(430, 20, 31, 20))
        self.springFloor_lineEdit.setFont(font2)
        self.springFloor_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.springAddBody_Button = QPushButton(self.collision_groupBox)
        self.springAddBody_Button.setObjectName(u"springAddBody_Button")
        self.springAddBody_Button.setEnabled(True)
        self.springAddBody_Button.setGeometry(QRect(170, 14, 41, 41))
        icon3 = QIcon()
        icon3.addFile(u"icons/addCapsule.png", QSize(), QIcon.Normal, QIcon.Off)
        self.springAddBody_Button.setIcon(icon3)
        self.springAddBody_Button.setIconSize(QSize(32, 32))
        self.springAddBody_Button.setCheckable(False)
        self.springAddBody_Button.setFlat(False)
        self.springRemoveBody_Button = QPushButton(self.collision_groupBox)
        self.springRemoveBody_Button.setObjectName(u"springRemoveBody_Button")
        self.springRemoveBody_Button.setEnabled(True)
        self.springRemoveBody_Button.setGeometry(QRect(220, 120, 41, 41))
        icon4 = QIcon()
        icon4.addFile(u"icons/removeCapsule.png", QSize(), QIcon.Normal, QIcon.Off)
        self.springRemoveBody_Button.setIcon(icon4)
        self.springRemoveBody_Button.setIconSize(QSize(32, 32))
        self.springClearBody_Button = QPushButton(self.collision_groupBox)
        self.springClearBody_Button.setObjectName(u"springClearBody_Button")
        self.springClearBody_Button.setEnabled(True)
        self.springClearBody_Button.setGeometry(QRect(270, 14, 41, 41))
        icon5 = QIcon()
        icon5.addFile(u"icons/clearCapsule.png", QSize(), QIcon.Normal, QIcon.Off)
        self.springClearBody_Button.setIcon(icon5)
        self.springClearBody_Button.setIconSize(QSize(32, 32))
        self.springAddPlane_Button = QPushButton(self.collision_groupBox)
        self.springAddPlane_Button.setObjectName(u"springAddPlane_Button")
        self.springAddPlane_Button.setEnabled(True)
        self.springAddPlane_Button.setGeometry(QRect(220, 14, 41, 41))
        icon6 = QIcon()
        icon6.addFile(u"icons/addPlane.png", QSize(), QIcon.Normal, QIcon.Off)
        self.springAddPlane_Button.setIcon(icon6)
        self.springAddPlane_Button.setIconSize(QSize(32, 32))
        self.springAddPlane_Button.setCheckable(False)
        self.springAddPlane_Button.setFlat(False)
        self.label_18 = QLabel(self.spring_groupBox)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setEnabled(False)
        self.label_18.setGeometry(QRect(230, -10, 61, 16))
        self.label_18.setFont(font2)
        self.springTension_lineEdit = QLineEdit(self.spring_groupBox)
        self.springTension_lineEdit.setObjectName(u"springTension_lineEdit")
        self.springTension_lineEdit.setEnabled(False)
        self.springTension_lineEdit.setGeometry(QRect(260, -20, 31, 20))
        self.springTension_lineEdit.setFont(font2)
        self.springTension_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.keyRange_groupBox = QGroupBox(self.spring_groupBox)
        self.keyRange_groupBox.setObjectName(u"keyRange_groupBox")
        self.keyRange_groupBox.setGeometry(QRect(0, 70, 331, 71))
        self.keyRange_groupBox.setFont(font2)
        self.springActive_radioButton = QRadioButton(self.keyRange_groupBox)
        self.springActive_radioButton.setObjectName(u"springActive_radioButton")
        self.springActive_radioButton.setGeometry(QRect(20, 20, 91, 17))
        self.springActive_radioButton.setFont(font2)
        self.springActive_radioButton.setChecked(True)
        self.springFrom_radioButton = QRadioButton(self.keyRange_groupBox)
        self.springFrom_radioButton.setObjectName(u"springFrom_radioButton")
        self.springFrom_radioButton.setGeometry(QRect(140, 20, 41, 17))
        self.springFrom_radioButton.setFont(font2)
        self.springFrom_lineEdit = QLineEdit(self.keyRange_groupBox)
        self.springFrom_lineEdit.setObjectName(u"springFrom_lineEdit")
        self.springFrom_lineEdit.setEnabled(False)
        self.springFrom_lineEdit.setGeometry(QRect(180, 20, 31, 20))
        self.springFrom_lineEdit.setFont(font2)
        self.springFrom_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_20 = QLabel(self.keyRange_groupBox)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(220, 20, 16, 16))
        self.label_20.setFont(font2)
        self.springEnd_lineEdit = QLineEdit(self.keyRange_groupBox)
        self.springEnd_lineEdit.setObjectName(u"springEnd_lineEdit")
        self.springEnd_lineEdit.setEnabled(False)
        self.springEnd_lineEdit.setGeometry(QRect(250, 20, 31, 20))
        self.springEnd_lineEdit.setFont(font2)
        self.springEnd_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_23 = QLabel(self.keyRange_groupBox)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setEnabled(False)
        self.label_23.setGeometry(QRect(30, 48, 61, 16))
        self.label_23.setFont(font2)
        self.springSubDiv_lineEdit = QLineEdit(self.keyRange_groupBox)
        self.springSubDiv_lineEdit.setObjectName(u"springSubDiv_lineEdit")
        self.springSubDiv_lineEdit.setEnabled(False)
        self.springSubDiv_lineEdit.setGeometry(QRect(60, 46, 31, 20))
        self.springSubDiv_lineEdit.setFont(font2)
        self.springSubDiv_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.springLoop_checkBox = QCheckBox(self.keyRange_groupBox)
        self.springLoop_checkBox.setObjectName(u"springLoop_checkBox")
        self.springLoop_checkBox.setGeometry(QRect(270, 50, 51, 16))
        self.springLoop_checkBox.setFont(font2)
        self.springLoop_checkBox.setChecked(False)
        self.springClearSubFrame_checkBox = QCheckBox(self.keyRange_groupBox)
        self.springClearSubFrame_checkBox.setObjectName(u"springClearSubFrame_checkBox")
        self.springClearSubFrame_checkBox.setEnabled(False)
        self.springClearSubFrame_checkBox.setGeometry(QRect(100, 50, 71, 16))
        self.springClearSubFrame_checkBox.setFont(font2)
        self.springClearSubFrame_checkBox.setChecked(True)
        self.springPoseMatch_checkBox = QCheckBox(self.keyRange_groupBox)
        self.springPoseMatch_checkBox.setObjectName(u"springPoseMatch_checkBox")
        self.springPoseMatch_checkBox.setEnabled(True)
        self.springPoseMatch_checkBox.setGeometry(QRect(190, 50, 71, 16))
        self.springPoseMatch_checkBox.setFont(font2)
        self.springPoseMatch_checkBox.setCheckable(True)
        self.springPoseMatch_checkBox.setChecked(False)
        self.shelf_button = QPushButton(self.spring_groupBox)
        self.shelf_button.setObjectName(u"shelf_button")
        self.shelf_button.setGeometry(QRect(310, 30, 30, 30))
        sizePolicy2 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.shelf_button.sizePolicy().hasHeightForWidth())
        self.shelf_button.setSizePolicy(sizePolicy2)
        self.shelf_button.setLayoutDirection(Qt.LeftToRight)
        self.shelf_button.setAutoFillBackground(False)
        icon7 = QIcon()
        icon7.addFile(u"icons/Shelf.png", QSize(), QIcon.Normal, QIcon.Off)
        self.shelf_button.setIcon(icon7)
        self.shelf_button.setIconSize(QSize(30, 30))
        self.shelf_button.setCheckable(False)
        self.shelf_button.setAutoRepeat(False)
        self.shelf_button.setAutoExclusive(False)
        self.shelf_button.setFlat(True)
        self.label_19 = QLabel(self.spring_groupBox)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(160, 42, 61, 16))
        self.label_19.setFont(font2)
        self.springExtend_lineEdit = QLineEdit(self.spring_groupBox)
        self.springExtend_lineEdit.setObjectName(u"springExtend_lineEdit")
        self.springExtend_lineEdit.setGeometry(QRect(190, 40, 31, 20))
        self.springExtend_lineEdit.setFont(font2)
        self.springExtend_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.groupBox = QGroupBox(self.spring_groupBox)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(150, 220, 91, 101))
        self.groupBox.setFont(font2)
        self.springBind_Button = QPushButton(self.groupBox)
        self.springBind_Button.setObjectName(u"springBind_Button")
        self.springBind_Button.setGeometry(QRect(10, 20, 71, 31))
        font4 = QFont()
        font4.setPointSize(10)
        font4.setBold(False)
        font4.setWeight(50)
        self.springBind_Button.setFont(font4)
        icon8 = QIcon()
        icon8.addFile(u"icons/ctrl_bind.png", QSize(), QIcon.Normal, QIcon.Off)
        self.springBind_Button.setIcon(icon8)
        self.springBind_Button.setIconSize(QSize(24, 24))
        self.springBake_Button = QPushButton(self.groupBox)
        self.springBake_Button.setObjectName(u"springBake_Button")
        self.springBake_Button.setEnabled(True)
        self.springBake_Button.setGeometry(QRect(10, 60, 71, 31))
        self.springBake_Button.setFont(font2)
        icon9 = QIcon()
        icon9.addFile(u"icons/ctrl_bake.png", QSize(), QIcon.Normal, QIcon.Off)
        self.springBake_Button.setIcon(icon9)
        self.springBake_Button.setIconSize(QSize(24, 24))
        self.springWind_Button = QPushButton(self.spring_groupBox)
        self.springWind_Button.setObjectName(u"springWind_Button")
        self.springWind_Button.setGeometry(QRect(250, 230, 81, 31))
        self.springWind_Button.setFont(font4)
        icon10 = QIcon()
        icon10.addFile(u"icons/wind.png", QSize(), QIcon.Normal, QIcon.Off)
        self.springWind_Button.setIcon(icon10)
        self.springWind_Button.setIconSize(QSize(24, 24))
        self.springInertia_lineEdit = QLineEdit(self.spring_groupBox)
        self.springInertia_lineEdit.setObjectName(u"springInertia_lineEdit")
        self.springInertia_lineEdit.setGeometry(QRect(270, 41, 31, 20))
        self.springInertia_lineEdit.setFont(font2)
        self.springInertia_lineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_24 = QLabel(self.spring_groupBox)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(240, 42, 61, 16))
        self.label_24.setFont(font2)
        self.label_24.raise_()
        self.label_15.raise_()
        self.collision_groupBox.raise_()
        self.springSpring_lineEdit.raise_()
        self.label_16.raise_()
        self.springSubs_lineEdit.raise_()
        self.label_17.raise_()
        self.springXspring_lineEdit.raise_()
        self.springBonePose_groupBox.raise_()
        self.springApply_Button.raise_()
        self.label_8.raise_()
        self.label_18.raise_()
        self.springTension_lineEdit.raise_()
        self.keyRange_groupBox.raise_()
        self.shelf_button.raise_()
        self.label_19.raise_()
        self.springExtend_lineEdit.raise_()
        self.groupBox.raise_()
        self.springWind_Button.raise_()
        self.springInertia_lineEdit.raise_()
        icon11 = QIcon()
        icon11.addFile(u"icons/spring.png", QSize(), QIcon.Normal, QIcon.Off)
        self.main_tab.addTab(self.spring_tab, icon11, "")
        self.main_textEdit = QTextEdit(self.centralwidget)
        self.main_textEdit.setObjectName(u"main_textEdit")
        self.main_textEdit.setGeometry(QRect(10, 410, 345, 200))
        sizePolicy3 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy3.setHorizontalStretch(200)
        sizePolicy3.setVerticalStretch(200)
        sizePolicy3.setHeightForWidth(self.main_textEdit.sizePolicy().hasHeightForWidth())
        self.main_textEdit.setSizePolicy(sizePolicy3)
        self.main_textEdit.setMinimumSize(QSize(345, 40))
        self.main_textEdit.setMaximumSize(QSize(345, 200))
        font5 = QFont()
        font5.setPointSize(8)
        self.main_textEdit.setFont(font5)
        self.main_textEdit.setReadOnly(True)
        self.main_progressBar = QProgressBar(self.centralwidget)
        self.main_progressBar.setObjectName(u"main_progressBar")
        self.main_progressBar.setGeometry(QRect(10, 375, 361, 27))
        font6 = QFont()
        font6.setFamily(u"Consolas")
        font6.setPointSize(12)
        self.main_progressBar.setFont(font6)
        self.main_progressBar.setAcceptDrops(False)
        self.main_progressBar.setValue(0)
        self.main_progressBar.setAlignment(Qt.AlignCenter)
        self.main_progressBar.setTextVisible(True)
        self.main_progressBar.setOrientation(Qt.Horizontal)
        self.main_progressBar.setInvertedAppearance(False)
        self.main_progressBar.setTextDirection(QProgressBar.TopToBottom)
        self.main_processLabel = QLabel(self.centralwidget)
        self.main_processLabel.setObjectName(u"main_processLabel")
        self.main_processLabel.setGeometry(QRect(13, 353, 231, 16))
        self.main_processLabel.setFont(font5)
        self.main_processLabel.setText(u"")
        self.link_pushButton = QPushButton(self.centralwidget)
        self.link_pushButton.setObjectName(u"link_pushButton")
        self.link_pushButton.setEnabled(True)
        self.link_pushButton.setGeometry(QRect(340, 342, 31, 31))
        font7 = QFont()
        font7.setUnderline(False)
        self.link_pushButton.setFont(font7)
        self.link_pushButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.link_pushButton.setMouseTracking(False)
        self.link_pushButton.setFocusPolicy(Qt.NoFocus)
        self.link_pushButton.setAutoFillBackground(False)
        icon12 = QIcon()
        icon12.addFile(u"icons/linkedin.png", QSize(), QIcon.Normal, QIcon.Off)
        self.link_pushButton.setIcon(icon12)
        self.link_pushButton.setIconSize(QSize(25, 25))
        self.link_pushButton.setCheckable(False)
        self.link_pushButton.setChecked(False)
        self.link_pushButton.setAutoDefault(False)
        self.link_pushButton.setFlat(True)
        self.miscUpdate_pushButton = QPushButton(self.centralwidget)
        self.miscUpdate_pushButton.setObjectName(u"miscUpdate_pushButton")
        self.miscUpdate_pushButton.setGeometry(QRect(220, 342, 31, 30))
        sizePolicy2.setHeightForWidth(self.miscUpdate_pushButton.sizePolicy().hasHeightForWidth())
        self.miscUpdate_pushButton.setSizePolicy(sizePolicy2)
        self.miscUpdate_pushButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.miscUpdate_pushButton.setLayoutDirection(Qt.LeftToRight)
        self.miscUpdate_pushButton.setAutoFillBackground(False)
        icon13 = QIcon()
        icon13.addFile(u"icons/update.png", QSize(), QIcon.Normal, QIcon.Off)
        self.miscUpdate_pushButton.setIcon(icon13)
        self.miscUpdate_pushButton.setIconSize(QSize(25, 25))
        self.miscUpdate_pushButton.setCheckable(False)
        self.miscUpdate_pushButton.setAutoRepeat(False)
        self.miscUpdate_pushButton.setAutoExclusive(False)
        self.miscUpdate_pushButton.setFlat(True)
        self.vimeo_pushButton = QPushButton(self.centralwidget)
        self.vimeo_pushButton.setObjectName(u"vimeo_pushButton")
        self.vimeo_pushButton.setEnabled(True)
        self.vimeo_pushButton.setGeometry(QRect(280, 342, 31, 31))
        self.vimeo_pushButton.setFont(font7)
        self.vimeo_pushButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.vimeo_pushButton.setMouseTracking(False)
        self.vimeo_pushButton.setFocusPolicy(Qt.NoFocus)
        self.vimeo_pushButton.setAutoFillBackground(False)
        icon14 = QIcon()
        icon14.addFile(u"icons/youtube.png", QSize(), QIcon.Normal, QIcon.Off)
        self.vimeo_pushButton.setIcon(icon14)
        self.vimeo_pushButton.setIconSize(QSize(25, 25))
        self.vimeo_pushButton.setCheckable(False)
        self.vimeo_pushButton.setChecked(False)
        self.vimeo_pushButton.setAutoDefault(False)
        self.vimeo_pushButton.setFlat(True)
        self.bilibili_pushButton = QPushButton(self.centralwidget)
        self.bilibili_pushButton.setObjectName(u"bilibili_pushButton")
        self.bilibili_pushButton.setEnabled(True)
        self.bilibili_pushButton.setGeometry(QRect(250, 342, 31, 31))
        self.bilibili_pushButton.setFont(font7)
        self.bilibili_pushButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.bilibili_pushButton.setMouseTracking(False)
        self.bilibili_pushButton.setFocusPolicy(Qt.NoFocus)
        self.bilibili_pushButton.setAutoFillBackground(False)
        icon15 = QIcon()
        icon15.addFile(u"icons/bilibili.png", QSize(), QIcon.Normal, QIcon.Off)
        self.bilibili_pushButton.setIcon(icon15)
        self.bilibili_pushButton.setIconSize(QSize(25, 25))
        self.bilibili_pushButton.setCheckable(False)
        self.bilibili_pushButton.setChecked(False)
        self.bilibili_pushButton.setAutoDefault(False)
        self.bilibili_pushButton.setFlat(True)
        self.language_button = QPushButton(self.centralwidget)
        self.language_button.setObjectName(u"language_button")
        self.language_button.setEnabled(True)
        self.language_button.setGeometry(QRect(310, 342, 31, 31))
        self.language_button.setFont(font7)
        self.language_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.language_button.setMouseTracking(False)
        self.language_button.setFocusPolicy(Qt.NoFocus)
        self.language_button.setAutoFillBackground(False)
        icon16 = QIcon()
        icon16.addFile(u"icons/language.png", QSize(), QIcon.Normal, QIcon.Off)
        self.language_button.setIcon(icon16)
        self.language_button.setIconSize(QSize(25, 25))
        self.language_button.setCheckable(False)
        self.language_button.setChecked(False)
        self.language_button.setAutoDefault(False)
        self.language_button.setFlat(True)
        self.main_lang_id = QLabel(self.centralwidget)
        self.main_lang_id.setObjectName(u"main_lang_id")
        self.main_lang_id.setGeometry(QRect(-50, 340, 21, 16))
        self.main_lang_id.setFont(font5)
        self.main_lang_id.setText(u"chn")
        self.spring_language_list = QListWidget(self.centralwidget)
        icon17 = QIcon()
        icon17.addFile(u"icons/China Flag.png", QSize(), QIcon.Normal, QIcon.Off)
        __qlistwidgetitem = QListWidgetItem(self.spring_language_list)
        __qlistwidgetitem.setTextAlignment(Qt.AlignHCenter|Qt.AlignVCenter|Qt.AlignCenter);
        __qlistwidgetitem.setIcon(icon17);
        __qlistwidgetitem.setFlags(Qt.ItemIsSelectable|Qt.ItemIsEnabled);
        icon18 = QIcon()
        icon18.addFile(u"icons/english.png", QSize(), QIcon.Normal, QIcon.Off)
        __qlistwidgetitem1 = QListWidgetItem(self.spring_language_list)
        __qlistwidgetitem1.setTextAlignment(Qt.AlignHCenter|Qt.AlignVCenter|Qt.AlignCenter);
        __qlistwidgetitem1.setIcon(icon18);
        __qlistwidgetitem1.setFlags(Qt.ItemIsSelectable|Qt.ItemIsEnabled);
        icon19 = QIcon()
        icon19.addFile(u"icons/japanese.png", QSize(), QIcon.Normal, QIcon.Off)
        __qlistwidgetitem2 = QListWidgetItem(self.spring_language_list)
        __qlistwidgetitem2.setTextAlignment(Qt.AlignHCenter|Qt.AlignVCenter|Qt.AlignCenter);
        __qlistwidgetitem2.setIcon(icon19);
        __qlistwidgetitem2.setFlags(Qt.ItemIsSelectable|Qt.ItemIsEnabled);
        self.spring_language_list.setObjectName(u"spring_language_list")
        self.spring_language_list.setGeometry(QRect(307, 235, 36, 111))
        font8 = QFont()
        font8.setKerning(False)
        self.spring_language_list.setFont(font8)
        self.spring_language_list.setAutoFillBackground(False)
        self.spring_language_list.setFrameShape(QFrame.NoFrame)
        self.spring_language_list.setFrameShadow(QFrame.Raised)
        self.spring_language_list.setLineWidth(0)
        self.spring_language_list.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.spring_language_list.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.spring_language_list.setFlow(QListView.LeftToRight)
        self.spring_language_list.setGridSize(QSize(36, 36))
        self.spring_language_list.setViewMode(QListView.IconMode)
        SpringMagic_mainWindow.setCentralWidget(self.centralwidget)
        self.main_processLabel.raise_()
        self.link_pushButton.raise_()
        self.main_tab.raise_()
        self.main_textEdit.raise_()
        self.main_progressBar.raise_()
        self.miscUpdate_pushButton.raise_()
        self.vimeo_pushButton.raise_()
        self.bilibili_pushButton.raise_()
        self.language_button.raise_()
        self.main_lang_id.raise_()
        self.spring_language_list.raise_()
        self.statusbar = QStatusBar(SpringMagic_mainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setEnabled(True)
        SpringMagic_mainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.main_tab, self.main_textEdit)

        self.retranslateUi(SpringMagic_mainWindow)
        self.springCapsule_checkBox.clicked.connect(self.label_23.setEnabled)
        self.springCapsule_checkBox.clicked.connect(self.springSubDiv_lineEdit.setEnabled)
        self.springCapsule_checkBox.clicked.connect(self.springClearSubFrame_checkBox.setEnabled)
        self.springCapsule_checkBox.clicked.connect(self.springFastMove_checkBox.setEnabled)
        self.springCapsule_checkBox.clicked.connect(self.label_18.setEnabled)
        self.springCapsule_checkBox.clicked.connect(self.springTension_lineEdit.setEnabled)
        self.springFrom_radioButton.toggled.connect(self.springFrom_lineEdit.setEnabled)
        self.springFrom_radioButton.toggled.connect(self.springEnd_lineEdit.setEnabled)

        self.main_tab.setCurrentIndex(1)
        self.link_pushButton.setDefault(False)
        self.vimeo_pushButton.setDefault(False)
        self.bilibili_pushButton.setDefault(False)
        self.language_button.setDefault(False)


        QMetaObject.connectSlotsByName(SpringMagic_mainWindow)
    # setupUi

    def retranslateUi(self, SpringMagic_mainWindow):
        self.main_actionReset.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Reset", None))
        self.main_actionAbout.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"About...", None))
#if QT_CONFIG(tooltip)
        self.main_tab.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.main_tab.setStatusTip("")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.main_tab.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.main_tab.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.main_tab.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.eng_groupBox.setTitle(QCoreApplication.translate("SpringMagic_mainWindow", u"\u611f\u8c22\u652f\u6301\uff01", None))
#if QT_CONFIG(tooltip)
        self.donatePayPal_button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>PayPal\u8f6c\u8d26</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.donatePayPal_button.setText("")
#if QT_CONFIG(tooltip)
        self.label_3.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u652f\u4ed8\u5b9d\u8f6c\u8d26</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_3.setText("")
#if QT_CONFIG(tooltip)
        self.label_21.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u5fae\u4fe1\u8f6c\u8d26</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_21.setText("")
        self.label_22.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-weight:400;\">Spring Magic \u662f\u4e00\u4e2a\u5b8c\u5168\u514d\u8d39\u7684\u811a\u672c\u5de5\u5177\uff0c\u4f60\u53ef\u4ee5\u65e0\u507f\u4f7f\u7528</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-weight:400;\">\u5b83\u7684</span><span style=\" font-family:'MS Shell Dlg 2';\">\u5168\u90e8\u529f\u80fd</span><span style=\" font-family:'MS Shell Dlg 2'; font-weight:400;\">\uff0c\u5982"
                        "\u679c\u89c9\u5f97\u8fd9\u4e2a\u5de5\u5177\u771f\u7684\u5e2e\u4e86\u4f60\u5f88\u5927\u7684\u5fd9...</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-size:11pt;\">\u8bf7\u6211\u559d\u676f\u5976\u8336\u600e\u4e48\u6837\uff1f</span></p></body></html>", None))
        self.label.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u7279\u522b\u611f\u8c22\uff1a<span style=\" font-weight:600;\">Benoit Degand</span> \u5e2e\u52a9\u6539\u8fdb\u6027\u80fd</p></body></html>", None))
        self.main_tab.setTabText(self.main_tab.indexOf(self.donate_tab), QCoreApplication.translate("SpringMagic_mainWindow", u"\u6253\u8d4f", None))
        self.spring_groupBox.setTitle(QCoreApplication.translate("SpringMagic_mainWindow", u"\u8ba1\u7b97\u98d8\u5e26", None))
        self.springSpring_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"0.7", None))
#if QT_CONFIG(tooltip)
        self.label_15.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u8303\u56f4\u4ece0-1\uff0c\u94fe\u6761\u6446\u52a8\u5e45\u5ea6\uff0c\u6570\u5b57\u8d8a\u5927\u7ed3\u679c\u8d8a\u67d4\u8f6f</p><p>\u6ce8\u610f\uff1a\u8ba1\u7b97\u53ea\u5bf9+X\u8f74\u671d\u5411\u5b50\u7269\u4f53\u7684\u9aa8\u9abc\u94fe\u6709\u6548</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_15.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u6446\u52a8", None))
        self.label_16.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Subs", None))
        self.springSubs_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"0", None))
#if QT_CONFIG(tooltip)
        self.label_17.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u8303\u56f4\u4ece0-1\uff0c\u62e7\u8f6c\u6548\u679c\uff08X\u8f74\uff09\u7684\u67d4\u8f6f\u5ea6\uff0c\u8d8a\u5927\u62e7\u5f97\u8d8a\u591a</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_17.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u62e7\u8f6c", None))
        self.springXspring_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"0.7", None))
        self.springBonePose_groupBox.setTitle(QCoreApplication.translate("SpringMagic_mainWindow", u"\u9aa8\u9abc\u59ff\u6001", None))
#if QT_CONFIG(tooltip)
        self.springBindPose_button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"\u56de\u5230\u8499\u76ae\u59ff\u6001", None))
#endif // QT_CONFIG(tooltip)
        self.springBindPose_button.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u8499\u76ae\u59ff\u6001", None))
#if QT_CONFIG(tooltip)
        self.springStraight_button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"\u6e05\u96f6\u65cb\u8f6c\u503c", None))
#endif // QT_CONFIG(tooltip)
        self.springStraight_button.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u62c9\u76f4", None))
#if QT_CONFIG(tooltip)
        self.springCopy_button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"\u590d\u5236\u6240\u9009\u7684\u9aa8\u9abc\u59ff\u52bf", None))
#endif // QT_CONFIG(tooltip)
        self.springCopy_button.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u590d\u5236", None))
#if QT_CONFIG(tooltip)
        self.springPaste_button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"\u7c98\u8d34\u9aa8\u9abc\u59ff\u52bf", None))
#endif // QT_CONFIG(tooltip)
        self.springPaste_button.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u7c98\u8d34", None))
#if QT_CONFIG(tooltip)
        self.springApply_Button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u4ec5\u8ba1\u7b97\u9009\u4e2d\u7684\u7269\u4f53</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springApply_Button.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u8ba1\u7b97", None))
        self.label_8.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"UpAxis", None))
        self.collision_groupBox.setTitle(QCoreApplication.translate("SpringMagic_mainWindow", u"\u78b0\u649e", None))
#if QT_CONFIG(tooltip)
        self.springCapsule_checkBox.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u52fe\u9009\u540e\u4f1a\u8ba1\u7b97\u98d8\u5e26\u4e0e\u573a\u666f\u4e2d\u80f6\u56ca\u4f53\u7684\u78b0\u649e</p><p>\u4f1a\u51cf\u6162\u8ba1\u7b97\u901f\u5ea6</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springCapsule_checkBox.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u542f\u7528", None))
#if QT_CONFIG(tooltip)
        self.springFastMove_checkBox.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u5982\u679c\u80f6\u56ca\u4f53\u9644\u52a0\u5728\u5feb\u901f\u79fb\u52a8\u7684\u7269\u4f53\u4e0a\uff0c\u6bd4\u5982\u5954\u8dd1\u4e2d\u7684\u53cc\u817f\u4e0e\u88d9\u5b50\u7684\u78b0\u649e\u3002\u52fe\u9009\u6b64\u9879\u65f6\uff0c\u53ef\u4ee5\u51cf\u5c11\u7a7f\u63d2\u3002</p><p>\u6ce8\u610f\uff1a\u5728\u78b0\u649e\u4f53\u79fb\u52a8\u8f83\u6162\u65f6\u52fe\u9009\u6b64\u9879\uff0c\u53ef\u80fd\u4f1a\u9020\u6210\u7ed3\u679c\u6296\u52a8\u3002</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springFastMove_checkBox.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u5feb\u901f\u79fb\u52a8", None))
#if QT_CONFIG(tooltip)
        self.springFloor_checkBox.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>Add a floor collition for joint chain</p><p>Script will trying to keep all the joints above the hight during caculation</p><p>\u542f\u7528\u5730\u9762\u78b0\u649e\uff0c\u8ba1\u7b97\u65f6\u4f1a\u5c3d\u91cf\u5c06\u9aa8\u9abc\u4fdd\u6301\u5728\u8bbe\u5b9a\u9ad8\u5ea6\u4e4b\u4e0a</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springFloor_checkBox.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"Floor", None))
#if QT_CONFIG(tooltip)
        self.springFloor_lineEdit.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>Floor height</p><p>\u5730\u9762\u9ad8\u5ea6</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springFloor_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"0.0", None))
#if QT_CONFIG(tooltip)
        self.springAddBody_Button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u521b\u5efa\u4e00\u4e2a\u80f6\u56ca\u4f53\uff0c\u5982\u679c\u4e0d\u9009\u62e9\u9aa8\u9abc\uff0c\u5219\u5728\u539f\u70b9\u751f\u6210\uff0c\u5982\u9009\u62e9\u9aa8\u9abc\uff0c\u5219\u8ddf\u9aa8\u9abc\u5927\u5c0f\u4f4d\u7f6e\u5bf9\u9f50</p><p>\u6ce8\u610f\uff1a\u53ef\u4ee5\u7f29\u653e\u79fb\u52a8\u4e2d\u95f4\u7684\u5706\u67f1\u5f62\u6765\u8c03\u6574\u80f6\u56ca\u4f53\u3002\u4e5f\u53ef\u4ee5\u5c06\u80f6\u56ca\u4f53\u8bbe\u4e3a\u5b50\u7269\u4f53\u6765\u8ddf\u968f\u7236\u7269\u4f53\u79fb\u52a8\u3002</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springAddBody_Button.setText("")
#if QT_CONFIG(tooltip)
        self.springRemoveBody_Button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"\u5220\u9664\u9009\u4e2d\u7684\u80f6\u56ca\u4f53", None))
#endif // QT_CONFIG(tooltip)
        self.springRemoveBody_Button.setText("")
#if QT_CONFIG(tooltip)
        self.springClearBody_Button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"\u6e05\u9664\u573a\u666f\u4e2d\u6240\u6709\u7684\u80f6\u56ca\u4f53", None))
#endif // QT_CONFIG(tooltip)
        self.springClearBody_Button.setText("")
#if QT_CONFIG(tooltip)
        self.springAddPlane_Button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u521b\u5efa\u4e00\u4e2a\u78b0\u649e\u5e73\u9762</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springAddPlane_Button.setText("")
#if QT_CONFIG(tooltip)
        self.label_18.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u94fe\u6761\u5f20\u529b\uff0c\u7528\u4e8e\u5b9a\u4e49\u7531\u78b0\u649e\u9020\u6210\u7684\u5f2f\u66f2\u5982\u4f55\u5728\u94fe\u6761\u4e2d\u4f20\u9012\uff0c\u4ec5\u5728\u78b0\u649e\u53d1\u751f\u65f6\u751f\u6548\u3002</p><p>\u9002\u5f53\u8bbe\u7f6e\u53ef\u51cf\u5c11\u78b0\u649e\u8ba1\u7b97\u7ed3\u679c\u7684\u6296\u52a8\u548c\u7a7f\u63d2\u3002</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_18.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u5f20\u529b", None))
        self.springTension_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"0.5", None))
        self.keyRange_groupBox.setTitle(QCoreApplication.translate("SpringMagic_mainWindow", u"\u8ba1\u7b97\u8303\u56f4", None))
#if QT_CONFIG(tooltip)
        self.springActive_radioButton.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"\u5f53\u524d\u65f6\u95f4\u8f74\u663e\u793a\u8303\u56f4", None))
#endif // QT_CONFIG(tooltip)
        self.springActive_radioButton.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u5f53\u524d\u65f6\u95f4\u8f74", None))
        self.springFrom_radioButton.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u4ece", None))
        self.springFrom_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"0", None))
        self.label_20.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u5230", None))
        self.springEnd_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"200", None))
#if QT_CONFIG(tooltip)
        self.label_23.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u5c06\u4e00\u5e27\u62c6\u5206\u6210\u82e5\u5e72\u788e\u5e27\u6765\u8fdb\u884c\u7ec6\u5206\u8ba1\u7b97\uff0c\u4ee5\u6355\u6349\u975e\u5e38\u5feb\u901f\u79fb\u52a8\u7684\u78b0\u649e\u4f53</p><p>\u76f8\u5e94\u7684\u4f1a\u6210\u500d\u589e\u52a0\u8ba1\u7b97\u65f6\u95f4\uff0c\u4f46\u80fd\u83b7\u5f97\u66f4\u7cbe\u7ec6\u7684\u6548\u679c</p><p>\u9ed8\u8ba4\u4e3a1\uff0c\u5982\u8bbe\u4e3a5\uff0c\u5219\u4f1a\u4ee51/5\u5e27\u4e3a\u6b65\u8fdb\u6765\u8ba1\u7b97</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_23.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u62c6\u5e27", None))
        self.springSubDiv_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"1", None))
#if QT_CONFIG(tooltip)
        self.springLoop_checkBox.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u662f\u5426\u5faa\u73af\u8ba1\u7b97\uff0c\u4ee5\u5bf9\u9f50\u9996\u5c3e\u5e27</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springLoop_checkBox.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u5faa\u73af", None))
#if QT_CONFIG(tooltip)
        self.springClearSubFrame_checkBox.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u5728\u8ba1\u7b97\u5b8c\u6210\u540e\u6e05\u7406\u4e0d\u5728\u6574\u6570\u4e0a\u7684\u7ec6\u788e\u5173\u952e\u5e27</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springClearSubFrame_checkBox.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u6e05\u7406\u788e\u5e27", None))
#if QT_CONFIG(tooltip)
        self.springPoseMatch_checkBox.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u4f7f\u8ba1\u7b97\u7ed3\u679c\u5c3d\u91cf\u8d34\u5408\u5df2\u6709\u7684\u9aa8\u9abc\u5173\u952e\u5e27</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springPoseMatch_checkBox.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u59ff\u6001\u62df\u5408", None))
#if QT_CONFIG(tooltip)
        self.shelf_button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"\u5728\u5f53\u524d\u4e66\u7b7e\u680f\u521b\u5efa\u5feb\u6377\u542f\u52a8\u56fe\u6807", None))
#endif // QT_CONFIG(tooltip)
        self.shelf_button.setText("")
#if QT_CONFIG(tooltip)
        self.label_19.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u8303\u56f4\u4ece0-1\uff0c\u7ed9\u9aa8\u9abc\u94fe\u589e\u52a0\u5f39\u6027\uff0c\u7528\u4e8e\u521b\u9020\u62c9\u4f38\u548c\u6324\u538b\u7684\u6548\u679c</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_19.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u4f38\u7f29", None))
        self.springExtend_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"0.0", None))
        self.groupBox.setTitle(QCoreApplication.translate("SpringMagic_mainWindow", u"\u63a7\u5236\u5668", None))
#if QT_CONFIG(tooltip)
        self.springBind_Button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u6839\u636e\u6240\u9009\u62e9\u7684\u52a8\u753b\u63a7\u5236\u5668\u6765\u521b\u5efa\u9aa8\u9abc\u94fe</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springBind_Button.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u7ed1\u5b9a", None))
#if QT_CONFIG(tooltip)
        self.springBake_Button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u5c06\u6240\u9009\u9aa8\u9abc\u94fe\u7684\u8ba1\u7b97\u7ed3\u679c\u70d8\u7119\u5230\u63a7\u5236\u5668\u4e0a</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springBake_Button.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u70d8\u7119", None))
#if QT_CONFIG(tooltip)
        self.springWind_Button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u521b\u5efa\u98ce\u5411\u63a7\u5236\u5668</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.springWind_Button.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u98ce", None))
        self.springInertia_lineEdit.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"0.0", None))
#if QT_CONFIG(tooltip)
        self.label_24.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"<html><head/><body><p>\u8303\u56f4\u4ece0-1\uff0c\u7ed9\u9aa8\u9abc\u94fe\u589e\u52a0\u60ef\u6027\uff0c\u4ea7\u751f\u4e00\u5b9a\u7684\u91cd\u91cf\u611f</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_24.setText(QCoreApplication.translate("SpringMagic_mainWindow", u"\u60ef\u6027", None))
        self.main_tab.setTabText(self.main_tab.indexOf(self.spring_tab), QCoreApplication.translate("SpringMagic_mainWindow", u"\u7b97\u98d8\u5e26", None))
        self.main_textEdit.setHtml(QCoreApplication.translate("SpringMagic_mainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-size:9pt;\">Created by Bai Yanbin</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'MS Shell Dlg 2'; font-size:9pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'MS Shell Dlg 2'; font-size:9pt;\"><br /></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.link_pushButton.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"\u4f5c\u8005\u4fe1\u606f", None))
#endif // QT_CONFIG(tooltip)
        self.link_pushButton.setText("")
#if QT_CONFIG(tooltip)
        self.miscUpdate_pushButton.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"\u6709\u65b0\u7248\u672c\uff01", None))
#endif // QT_CONFIG(tooltip)
        self.miscUpdate_pushButton.setText("")
#if QT_CONFIG(tooltip)
        self.vimeo_pushButton.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"YouTube \u82f1\u6587\u6559\u7a0b", None))
#endif // QT_CONFIG(tooltip)
        self.vimeo_pushButton.setText("")
#if QT_CONFIG(tooltip)
        self.bilibili_pushButton.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"bilibili \u4e2d\u6587\u6559\u7a0b", None))
#endif // QT_CONFIG(tooltip)
        self.bilibili_pushButton.setText("")
#if QT_CONFIG(tooltip)
        self.language_button.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"\u8bed\u8a00\u8bbe\u7f6e", None))
#endif // QT_CONFIG(tooltip)
        self.language_button.setText("")

        __sortingEnabled = self.spring_language_list.isSortingEnabled()
        self.spring_language_list.setSortingEnabled(False)
#if QT_CONFIG(tooltip)
        ___qlistwidgetitem = self.spring_language_list.item(0)
#endif
#if QT_CONFIG(tooltip)
        ___qlistwidgetitem.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"\u7b80\u4f53\u4e2d\u6587", None));
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        ___qlistwidgetitem1 = self.spring_language_list.item(1)
#endif
#if QT_CONFIG(tooltip)
        ___qlistwidgetitem1.setToolTip(QCoreApplication.translate("SpringMagic_mainWindow", u"English", None));
#endif // QT_CONFIG(tooltip)
        self.spring_language_list.setSortingEnabled(__sortingEnabled)

        pass
    # retranslateUi

